---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart rest-server
  ansible.builtin.service:
    name: rest-server
    state: restarted
  become: true
