$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
palette:
  kube-blue: '#326CE5'
  kube-red: '#FF0000'
  ubu-orange: '#E95420'
  debian-red: '#A90232'
  debian-purple: '#D70A53'
  rpi-red: '#c7053d'
  mac-gray: '#707070'
  microsoft-blue: '#00A4EF'
blocks:
  - type: prompt
    alignment: left
    segments:
      - properties:
          cache_duration: none
        template: ' {{.Icon}} '
        foreground: 'white'
        background: '#E95420'
        background_templates:
          - '{{if eq .Icon ""}}p:debian-red{{end}}'
          - '{{if eq .Icon ""}}p:ubu-orange{{end}}'
          - '{{if eq .Icon ""}}p:rpi-red{{end}}'
          - '{{if eq .Icon ""}}p:mac-gray{{end}}'
          - '{{if .WSL}}p:microsoft-blue{{end}}'
        type: os
        style: powerline
      - properties:
          cache_duration: 30
        template: '  '
        foreground: '#100e23'
        powerline_symbol: 
        background: '#ffe9aa'
        type: root
        style: powerline
      - properties:
          cache_duration: 60
        template: ' {{ .UserName }}@{{ .HostName }} '
        foreground: 'white'
        powerline_symbol: 
        background: 'black'
        type: session
        style: powerline
      - background: p:kube-blue
        background_templates:
          - '{{ if contains "prod" .Context }}p:kube-red{{ end }}'
        foreground: '#282828'
        style: powerline
        powerline_symbol: 
        template: ' ⎈ | {{ .Context }}{{if .Namespace }}:{{ .Namespace }} {{ end }}'
        type: kubectl
      - properties:
          cache_duration: none
          folder_icon: 
          folder_separator_icon: '  '
          style: agnoster_short
        template: ' {{ .Path }} '
        foreground: '#100e23'
        powerline_symbol: 
        background: '#458588'
        type: path
        style: powerline
      - properties:
          branch_icon: ' '
          branch_identical_icon: ●
          branch_max_length: 25
          cache_duration: none
          fetch_stash_count: true
          fetch_status: true
        leading_diamond: 
        trailing_diamond: 
        template: ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
        foreground: '#282828'
        powerline_symbol: 
        background: '#98971A'
        type: git
        style: powerline
        background_templates:
          - '{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}'
          - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}'
          - '{{ if gt .Ahead 0 }}#B388FF{{ end }}'
          - '{{ if gt .Behind 0 }}#B388FF{{ end }}'
      - properties:
          cache_duration: 60
        template: '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} '
        foreground: '#100e23'
        powerline_symbol: 
        background: '#4B8BBE'
        type: python
        style: powerline
      - properties:
          cache_duration: none
        template: '  '
        foreground: '#ffffff'
        powerline_symbol: 
        background: '#ff8080'
        type: status
        style: powerline
  - type: prompt
    alignment: left
    segments:
      - properties:
          cache_duration: 60
        template: '❯ '
        foreground: '#007ACC'
        type: text
        style: plain
    newline: true
version: 3
transient_prompt:
  background: transparent
  foreground: '#ffffff'
  template: '{{ .Shell }}> '
console_title_template: "{{.UserName}}@{{.HostName}}:{{.PWD}}$"
