---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k3s
  namespace: traefik
spec:
  secretName: wildcard-k3s-tls
  dnsNames:
    - "*.k3s.<your-domain.tld>"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
