---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-token
  namespace: forgejo-runner
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    token: AgAP2JWxhYerr5SuiilWudFgh9GULyte+ya+qbizF4TCUQNsJxkmusT/rAdtMVnFTZZ3Nqbl/odQon3PIKCbgBgQVT5GPj6PDTNqlHKJdiHppNCl6P/zJIo0jw//WRiRlr0A4guhb0I4HSaOUPZvvL7TP437kuk1XScQfdZvQG/O1J5cBANkoQY/kw4wERwfZXeQju+NkrV/c8Uc/bz75mRroH8kTzdB3G8Yhk78+9n9cA7pjk2IqzR9MjVaonWVdgFGMhShSXs+YtxdKMaxhC2U6zRYjhhv+1Thfi5dJL37emCSQ5Y/SBA03nYr+IXcsN16yV04X3Q4I2/JuEhZzBBvUleZOcXd3hbbrIO0G6JDaWL1FG/QTxe+2hfGJPGwLy3C9w1VfJHBg8nhcr1GqsHiPNlyKDR5UsAhLN+pydUk6VwmrA35BMKvPGN8u+keJsY4K9GDQ+l4WEmL2LyTTkF3jo7tGwMJ+6Hqj5hkrrXr+b5HVuKsfNXBeJZXHGNdY3o3rroTrwEBBKpBgq8xqSatC3666EtPjwiDVTSyfZ/pFKwGEHrvjLfmGrf+8XSDLGarZ11NQQ7czT9BxOYWhwOv50coihLSNAnXLOOpe4ue/gbEmE27f2xx02SZfxVOIeJTxT+I/lle/9sjOpAYT1xdgYxoDgGjnHrmVUXAYLYNCmE7vy/Ke+XkmOBAEU0Dwq7xpU46uEf0LLMylssgslKP1RmHwD8y9hUyoMJcauwMXMRZvwIc2wOB
  template:
    metadata:
      name: forgejo-runner-token
      namespace: forgejo-runner
