---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgB9qNKxUdy0NGkG7iXsKNyI5UjCcPLSfgGGcc36MEhQA6BalfPzfEQZIGHyFqo8H3+Mtcwgo+gCH854SQk3yCygwxFOwR4+Pa6FCobxNq6zs5YlqSgzcpDtf3AURpkET1AwR9Vb2piI/7l2iu084JbCVu7H5gpY+JWQZDIF3Ownvbei9Y19qMbKbFOdygf55AQRsSL/ykW0PVtggQbuQvYIJzzQy3JtJXdiMrVcJ1xDKtj8F7OIJryZbZJ8o8Q/rU+D1VcHseeGfzuzTzFs40JpuOy6hNPa7w1alCuLuJv92vC5kjNmgOATbp52NTLFM3PYLMQKcZw4PkU23eMl1pCEdUAi/k0B2Sjb8qufQXGXYY06DZvfCC7Z/DZeGJHEYoaAwffQdteedijDTV1Tvtc7NCtZC99wTRuEs1xjSzNdsBdxw3QREZDc28OZh4JExegFN/wa2eDFdptN7eK2B+UZYBj7DRZG8DSyZzI2SddzKIR8PqcX6+PCLGyLYq2gYPRTn9gQvu5q0W5QSCH705cfgy1QPQhAMkCK1nRaCgdL+8VDKexRIcLtiMA9LMrFuW51/hROx0CGnKX/vnmnhecY/7B/z0fhKO4JGjepDK+er3TQxBPQ18ByJbzcuknlVCloxKyk48Mh8Mef8JKsK9qVw8+chLPs7yRbHjBKYx1vKlSHDq8vlasjSOa8oSPjAB3IBF6Yzra7opF6qn2X0fhCRp/4cj3WxeOecAtkTRzg4tjfhoP+JL4FVvR0/o0H4omB0TS8IkyzjwYhCj4FZqSo
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
