---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgB9oAI3w9KTNJOevwOnhfFKcmG/GXi+3i6XgMC1wPQivN2wRnsw+jr66/lf1n1puBms1Pmtx+8zjkiQmGBxey/uu/QRd8IpyNmb2B1S58MOu1er6e7f1LWPxA5BhEIoHlgZ0FSmDgFZ8Q4ZHK2o2YqNXg7Cb18jxYB1XexYeJGXxOTyYWel1logwl/yloyUSxFQmzWQm036a7wCKnxeb0pZcz5mdlfltawNlMYL6pscO6fnapp7DVsomuESHBbcn0NPDIne940JRJIbca8z2lWiRjvjUP0mz4aP8PcOFKiUKdzdBYvVORiuqjXTEpauSaqy2fLBBQFBF+ST4ZMifBL/MvA+So5Hnoz2n6S4CrIrgwH/5Da4NrkYB1a2djHFVH7C2p6ulYGl1ujjEYXScnf44SiVpNr6isyzd6Rk8eYF3kstIBVv23XI3+7jLrI+SOt62umxw2BSR3EkKVaoffNN3rB0F4dUuxAi874H1guBjonOKW6FQ31U611xob1sZtZGxISBkbklM5vYhh1xMieOJPSy5a2CYb/dIiIMzvA6l5sgD49PadcRtp3QX8JWlNOfN9loqimY+MNP5oyxlqggfs3OJZGIDLexhwQ+mM4uxUgSoTuzFccuEvMA5WIttFkiY6QKM3P97u9I+lnA2eFOdt97I/aJnK2g0o1pLIKGkTKhGnTsGtrOYj6408dPN1LFxg/p+PM4f3Ul9useIgBzbvy2tXUEMhrS3WfNSFMTYYeu5AadCRzXo+Vsx0TlvU7fggLqNVKE12pZenjPKwN9
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
