---
# ArgoCD application-controller metrics (port 8082)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
---
# ArgoCD server metrics (port 8083)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server-metrics
  namespace: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
---
# ArgoCD repo-server metrics (port 8084)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server-metrics
  namespace: argocd
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
