---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-forgejo-oauth2
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: authentik-forgejo-oauth2
  data:
    - secretKey: client-secret
      remoteRef:
        key: k3s/oauth2/forgejo
        property: client-secret
