---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-argocd-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgBk70gahXdvnfd+882o89q4JM5ik8dC42q5Qva2eJwOf2GCXvNm2MxuDHkMZuo2zOI5rvRHXVy65Lu7N5pezMCUdroK5KQmagyPMOQn/vDaHl6OiWTJv1rGvt3rcFB2tYBFC82GCB+my2KflPvHbS4XS0Xt5QX8X5+VJPJaV/ppedkWlIn3Jc72LoBxuMqOF3KI/teii3y1vqIQEZMR5D6X2at+UKNyH1eLROLhFndOFofcVJ5u7jjDNJX6oKHMGnT3W6tIvmQUhstwjaVRRiw/KreqDvxBN0nGCskp71fvNYJz4VraJmAQQ62vPVbl0bE93u0SiYbXeFlo84EfYPkNlB6bm0WuY1DtV+NGqMIy4Fj2mKeSnLSaH+f7T1q73C2zctQSrXVl5aw9IykzuSkozTuQVchyer0bUPQnn/QMqE9lI5YDttB43Gn0z2uaeSNJnmqcvEsNlXAG1MKLF1RxBTgL651F/rgg6lS2TF6GaXTQbnu++keyX7xZjSPAHPWwG3H6BlU4jk524EjeEB9u9iXG+Cq0Xejt68WpOIea59MfllvT+LJ1K/1tutCkGhUsKMuwWzmlfbnSo7pK148K9S+ZoPOjrGZ1p3MKd0LV9G1aErcZFJxXymMFBXgMo7vN8MhmWuYji1oHRDA3QQamfnSCzNVClkJyVabuyJeAfvU5RRbjwtnVoMLj2mcJy2sfgqczXQt8s5GelBnQuBS4K9fVDwlxxZTj3TqtrPxIYvLbrbdySMBLdL1YOXrdntj4euqC1Rsb15CnSXO1/rGv
  template:
    metadata:
      name: authentik-argocd-oauth2
      namespace: authentik
