---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-wikijs-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgCAatFwfKWP8XRqS4WfQr3gSd79VzRXui8lzM/KFeOMlRhkHScbG9WESrh0DNG01smLLH6962Y6gf8pjvljHQgwr9iIfenoY6ExXqTNsgewT5OKGjGIw0AITjwbBovC35N8hxbFl7KDOJ7SR477Xrstnjx5e4ghbtrLgIhzHD+2LSOZeSKM9sQLyjcjyCnv+kpVIcXfsu7CHLGzJp48vONaFDrDdrc7I8pLUegib6GxJVL/f6doQSUK6x9bwjFadW7Yvg7TlrzQduoDdqMW0epzBXSCWh7lqpOvG83reaUk3cP2GnlQCF6ST2Nb45in82O/jo/B5eHjdBU/gq5XTSYXbQCLf+O5vTZfWJpWoVwZemv6r5AXca25iNFNhiEUw1gh0m4JoQcu8hwecL40UuO1OHinswGK43rtOK3WfBgGrJzu31Tgs0E7kDiIdCAQNQve2focedLjj4HoBj/nSO30e3QeNJx7uW9aE/tamhHi4EE6vJcpkKrmng9LE2E8ixTLLhUvnmRKCFxO5GrTDENsoqE3ha4KR5+SJ52yQkggOpNsyc+jxboxLw3KaKlXgVk2JxctxUmNZDjgK6zQbYdZC5Gl/KPNoi//NBLuQY8/B7q0vXqNNXBVzKdj41b21BrVsbz0rzXNyKkKZzyuhOyCdT3gehjb7Mnoe0/hqmL1Cz5g9IT2XX/GzlNx7nUeXHPMse797ug8JwzGCYLEZhql1hva4X5UlemIV88qZmxhHeRK7kpEjTm0Ga5LJTOOlyw+y/PltE+AXO6msg8dCNAK
  template:
    metadata:
      name: authentik-wikijs-oauth2
      namespace: authentik
