---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-forgejo-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgAjLIXqH0zBXUE/QEFBEiX6USetytOoL6EJ18VUFUaYyeL82ohmxitL4/gZOjmNpwo03pMizeVLrtStlDMb+UECLqlSxC46KCKzX1OhIbVtNjmzVSaYHwUW2sLoF1PM0ob6qpRFTrT6MVACkKJtyclYxEUsobcRnd87Jr+UPmgRUToUsvOSEfMnDCtddN0l8BAa3MmTrSJAU7l2WidV/tT7lMAQDn//oeN06r08/q/z394vkUFIf6GFP2s9h/+boHYx+OT04EZ0I2k3gJfSl/j3FHIS1VE/kJ3ivA7Dmayss42ZwMgEoT2DrFv9/OauSVOp9vdjX91Htq/JqN9CjP5Rx7mi0EBc8ROEzN2dcif+sLF3DL+ialbNDgcco1OdFVBDo1Qk7O3NrpPDw7JwIWcJT22fsBs5zcNghTwkjqHTSS4nU+pV8bDTRGxpaww8cN4IiJ/i34saaZVdL658IkSTVeT/aD1xU8X7iorJsU3Z7VZaopyJ7S4zTG2uftDCuXNbf1K60NBLDgaN6CwfYDdKmlLDyM7gSeydQBcSOVC4ZxHPV4d2iFoqLJ1md8IyZjtyhhdOTwXMNKtR0AAEughF+/93Cdw/vyb1RZ8t4T5MPfjLZjah1I5y+U3khzUEZ6gTJK56meFA1kGVu7p7LYgKEidslpL3NSci/qoCQ85nIToNnLtXZ+xehC4HZHKTPGvhcN6p7BhewfImzG5mu3lZGRV74RSfHBsn72QeIfAmTDtEU/vEtMDOYpSX+J2saLE=
  template:
    metadata:
      name: authentik-forgejo-oauth2
      namespace: authentik
