---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-app
  namespace: wikijs
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    postgresql-password: AgDVvBKOwAGwZdyRr1CrOocVejmqBFuJ4ERfhMy7ogOwg4n2yygxJB86T2OlKjEXv2WSxN+4NHAUTUFA0oWXeOYGpv5wLrtNUmFh9G4YyBc0blBSoZUJWFHL5X/ymuAXZX+j990AEpoF/SQa+Wl4QA0iZCD0PCTSHvi7w9XdadWZurbFg1m/xLfHFBKzKOmsONqIvJD+PO8Fywl7Fuyqia2omwtVXLTl232PODzSxixREFZZQggk9ZXHj0cm1IIc33Zc5QZNiTyI8UFQAQpxixDJ3p1ewjRMvZXgq5QlLU8RB8I4z8g7V1+NmbX/ub06dpsO60DY3/NBqUgV4d46iOASTXqI8rWUxN3khQ2AUdRNSv+y7VRtHvli4mvlwvGw3oHIoRfeCsLaq+gEmOsNjVmeZe/pqr4qZM57NlU1T4SOn3GP6GTtKCWAP4sVnbQluvXLijV64rtt9gLNAMshYSZfdvZz+wZBYr/9ER1LZFRs15vsjjDVyHyk/Mz28BzWICHuqEcRfeo/2s1etxoQy93F/L/q1wbnILT9s+wXLe9TXLRJanEYff4hTI03dUQJLobd7mMfuCx40RL1rWm/rJWpQETwRACb3x9sXbmqBY0u4O8Ub5ZXZ1/X3wFrpaRnPZys4Y5BSB3AhKRI/onwqFWFRAWqCwt9gSKiKGngRSEIWFwyaRj78/NTZ/fXeX6ccyCTN6jDBllTsjBQo7CRVlxUJYrrPhD9p87XCYidvdFAHIPaTeCLAz+PrGXS/bvFao/6qQAAIlD9is1tKLy8wxK5
  template:
    metadata:
      name: wikijs-app
      namespace: wikijs
