---
roles:
  - name: markosamuli.linuxbrew
    version: v2.0.2

collections:
  - name: community.general
  - name: ansible.posix
  - name: kubernetes.core
    version: ">=4.0.0"
  - name: https://github.com/kubernetes-sigs/kubespray
    type: git
    version: release-2.29
