---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
data:
  app.ini: |
    APP_NAME = Forgejo
    RUN_USER = git
    RUN_MODE = prod
    WORK_PATH = /data

    [server]
    DOMAIN           = forgejo.kecskemethy.org
    ROOT_URL         = https://forgejo.kecskemethy.org/
    HTTP_PORT        = 3000
    SSH_DOMAIN       = forgejo.kecskemethy.org
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 2222
    START_SSH_SERVER = true
    OFFLINE_MODE     = false
    APP_DATA_PATH    = /data/forgejo

    [database]
    DB_TYPE = postgres
    HOST    = postgres-rw.postgres.svc.cluster.local:5432
    NAME    = forgejo
    USER    = forgejo

    [repository]
    DEFAULT_BRANCH = main

    [session]
    PROVIDER = db

    [cache]
    ADAPTER = memory

    [queue]
    TYPE = level

    [indexer]
    ISSUE_INDEXER_TYPE = bleve

    [service]
    DISABLE_REGISTRATION = true

    [security]
    INSTALL_LOCK = true
