---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: forgejo-db-credentials
  data:
    - secretKey: password
      remoteRef:
        key: k8s/db/forgejo
        property: password
