---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-authentik-oauth2
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: forgejo-authentik-oauth2
  data:
    - secretKey: client-secret
      remoteRef:
        key: k8s/oauth2/forgejo
        property: client-secret
