---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-secret-key
  namespace: forgejo
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    internal-token: AgAQrhVGC43bseGmY6sISWoE9xw7Ek1/RU/vI8WqZUsvbm5ztmEmXbLwYyfmWzQ1nLdKyaSJA/O2ILG8hvtnVSH+jM6kJTaseykWT/iJBv+juDM038Hhg2fpDtoxd/G40JXBu2c+efqJRNMGWAlJYbISpghePsw3+jM7yQHzvFH0DyS3nFfUEZI7Vxu3RfuUB2dqegT4fUhnYcwZQ6HJojVJ/LVo9BHbeo75j/Q8ChRN4wVJCRtIGhjdYq2cnNMAZAPZWX2mHN8TTptDc8nw2dbVa8ROpvpflXOKqyTWktPwJH8CEog4sjVONg7D+6i2TaS5wBx7DEhIJzNBT8zIKDQdGGcZsCmLXK2kCO1MyBUvJHCqlKgxyIlmfeKIJmfqpeNwcyuiQ/xJOd4VFvr7zWZ3OFksbv0zajMeZGggMRsUSQJYH6cLkaugX57q3ewDATnoX4vHt7j8PhOUQsddsWYJB1RMT5tdZgbe0l/UHC7OTYvcEbKq+seVi/J50vFKMdRpXA3+VVpQQJ6A1krT4E9uFz7gOPKvLARw8+cNMhz0wF5l3JvVTXyMyC/7TImrv9ZsFUM0SYxgodCfn2NQCN/I4DxIOuOePhrfgZ5CzzoeybfDD7P/Ctop+JoMy182sHj4HxIeO/6j1c+OhCQbqG64nLZBD4yZxSb6ABwFBIiOmoo0y1FZGNG1v2EdmmA6lsFOnbd+LS2gwopSRvNPNL9hVi+q+8VcqPdh7LqCk50dxH5x54dWCHvh1SaFIqTrtuYnwtbYBRruk6zlV+38VOzl
    # yamllint disable-line rule:line-length
    secret-key: AgA5T+1NtQjuYvLhdM8FLV7r6fOS6TSfGQ1f1Nq/ZQfFVdDlwbwUElfqWyyRHsoCQVG5baX0l3MDx2AU413UWy1MimM0foLDBTfpQ+RTSCcv/8UzJBC5npBE2Zw93UDiGQEU4SFSfLOyrfy7U5q1onG3cfia+rT16Npxfk576Hg/32VvP9Ikx/8Ev42oX9tw6casY8YGnC1QnX7VhM91XBnLB/uY4iOYEfFxzM69BdoGAbiqfurZrLELB3InKE2L0fyK7NgkwF3R3cmSbJ8iP/AwsobCqmv7J1W/cpmBSltw8At3DqD8m3ak5+Ve3XTVL/w37gkmqHHhV3lEN3ibaxPXkthZYUZQw0vPqmfbprKzt6qszFPuG0pgoihmcxEOeVpTkI/LhT86WCvOPvKAVBMOlchV0L+xn9vqwM/0N7YD209oPw4guNxaqT4UyAT2NUwC+4zfI2/24kqb61ZKoBVyTlYJJ3Mt6cBvkcmUm4ZQ7FAgPxTs9b1r18YgZYPk8y8MzSqVATaWxmaXs+YKBlplNTvwLOdTOrP1YET33jxT2Dg2dlw1NH1jPsiNZ5CHaVuXt1lb8mfNw1SQ5rBAgg7h+p+AO7KkfGgqz6seBGySkR74LdxPW70anHfx6k1EUVQomRkz20YOAyazSBkigPakn3EcbmpC8KJzJiwLlfMVUmzenwGoV9NxUq87TOac8Jf+GGUqy0jxAb/lAUGj8VPPrDyxAjSpVrbkvQRE0NqGSjj8jICCu6/ZHGT72a/2Z37T64HKGmx6t8gcPKF/dfN9
  template:
    metadata:
      name: forgejo-secret-key
      namespace: forgejo
