---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgDgsZfkqeFOCWV3L2mwGmyt9CRe/WKszde8nY5Ws4bATAQsmRrTg9V2F1FsSK3d6VhWFC79w1fqB3VUvX1mf2PtjISMsVJW9dHh4xnVnK2y4W+pqkUCcYBrMo3wxlaEf7p2i3p1ilFOi/fZAjBN0W1dT7V/E6I2NfW5EJmn+KQe+c9h5b8jl2DUtAzGmDdfYTnBlDe1Lm18ih8RgCjHFVCkotcuuZizLiA+GO0lrMQtQqB+iknIP9gq+4VPqp79HqyEiRNs3ao2uARqZUaapLfi9gaEsY7es9Qs35apImIPd6kvaEgFbonH3HU7qF+ncDENjVAd5i5frGogw8xomPRdTD636quSsO9laHWCWWfjFVu//5yiW/xBgjAGRSw7umqKKt5Oxhaf7jwXMWMufqgn+QPxVd2dLoOvhEL7LK36J0BhQ9focb1iaWjP5svK1A+S9kJwDp1Ob4Y9TiZgajng7FLPcjuFmGdWvw3xKFCLj41PZqlNYGimZDeBjvT6GhEKvc9sCTNVMWmv+XW3iWeyH8bS9//HmjQttM3vQ0GVU/L6Kyrb6MAO9kTbFttO8Sg89TPHtMzWypb7fGpyGG+9yzVBQKwr0v1ldF3yQBGN9hco1UZU0+/X/6tXQodNUFtg+5gyHx7fTUSt8yiemLhe+wAD+1KSMZOOyTSsXxys/XbZNrnCF4tLCMOlyc5DaToCuYiYHrlsSAR7W58Wfy6M4UfDuGQBuiimSUkSPvvH9Q==
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: forgejo
