---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-authentik-oauth2
  namespace: forgejo
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgDYBn4a2DZY43O5Vut2+DysTuNaOvxZPDnBYtsEv5waN1quXiHJfZBCKv5BwRLtQzsPfqiavOMKeUDgorc76G2D/AIJaUOShR2qCzT9CSS/RzA6qLqut5j62skiaQq6NVMy6q6FE7TMSug4NAJANLgjjp5X1uV62NqokGTZxw+8Q69pQiQki5TH2pV+S2SwCYBWM262zVvursJF53TqDyePIAF/hTTwMUDXa2/w/NI175SnP44wlJhN4B4xve6vlhkWH5LczSBa4EXeQoiMGN9RdHYjTFnlrwpbKc6yzkuKutg4EAV+TrVldhiYatdmfeJJzkg5E3OqiRgWttsZHpfrlmJAin2jV4hK3PVpG3FAi5dYQm3TYpG1e+nCEgQo/siZgGq7z3Y4FSefIq1GdwWp6Zcs8t4sTSjZkq72JTjROnQHU99GJ3eg6PMb+ZJb3R90xOKXzM7twGdr8E7mMAr9lBkOJz/0cwz9Jwkt6CnwtKljGokKJKm4Cc2b/kZTDG6apSjzfLlfixMbhl8t/8TQxSBVB7stC+8CfIDx3wPxxA11m0NnPb+YwhWMcv15yQxSG2Izf29MyRK4tsoglPdtIk9BtFAT7BUo9NcRat2Tw7fnCyuVq1c0oBkqeFwmbg0Gj8YO+Fb81IOSMQB7TzhLhisW6AklKAtlx2gfHX6FAhUykS5DoumOMzxNRUAWyd22W9cXIZB3i1XRjKQFQ6qAcWVPX9eELTJspDbBjs9cT3qaFjpt2wAHmDLKXw==
  template:
    metadata:
      name: forgejo-authentik-oauth2
      namespace: forgejo
