---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikijs-app
  namespace: wikijs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: wikijs-app
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: k8s/db/wikijs
        property: password
