---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-app
  namespace: wikijs
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    postgresql-password: AgCQugbaSiN/WQ4Sl9dUwxCmDD0Qle+SBL4txMpDfVXQJPynRosjK5z4DxdYzGNnit5oDmCpJafSF26G8UWX3RdeHUrvBMkztw/JFsJJD0WuWuoutxJCPgAxIxmMzPG4CO2cSP5qR9EO9ekEfxs4b51oMUGCWXYf1VUuGKGBHmakuLjGAeZiPh75zwVrnhF1HWrK/VO5MEiHNQAS5+E2FShBPb35g1pkrnAwDonwu3iUIkPRU6NTi6SEt0ScQ++iq4BA5Uvi3nZ8l2BoWqdfgSiYSSyETREzV67ihERuFvpkQHmV8kREiLKYtbO7l+ztZnG2ObUn8xXGvcolbhVN00oQfPCgtVkdeA7pe9PZEpTf8iygxcsgyjs+6YLnDhV+B2N33nTTEX7GvbRrnXs+ykQnfEXZjCqdoffB21es1+Jla2joQxUprcor5HFmZUnrlV3pnyBqrGXSIhRzCFCKDgF8Mf7LxHYhNXcBkqgVKcuhy2kjGJEg1CFFrdXjjByYs9ja1weQJK7FraS8iJC2Fb1uF2mr6ZSvJGOMVMzaDofweTanB8dg27gcWTgPLiOrk3CWZuYPgOTuzFS8u2Cv6joKmKoBlbdyu4B+qvkF5kovnbMRc1rBgd2SSLtEyL6UDiWDWPlDqvRmg0V0hXUv85GZsM9GgUKIBZCTzgx2rGh/5gwTLKHj1jRfQmrPwxKrkJ5G6IVeHhrQ5V4mR5c0yGFHbDgPBg2xeCG+jjI7dkz95g==
  template:
    metadata:
      name: wikijs-app
      namespace: wikijs
