---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: mealie
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgCdaXYHsL45Gh9MFN2W+Ewux8IVw9NB3jewuXDdQUtIPwL7yAR70RDlg0HqEFjSzRsa0CGBhFLTG+nACVMJuQQYD+5aTPtEYhP5Ll1QZfwV6esuH8uk5x8fMJwnZKOVAO6WMMmwi2eVIvAnxpV835Pv0F+5n5zjS3xz/Z9BNdXeOJABIlYJYRY1vE3JZxOGKMUyv2/lwKeOyfTrQk8C1EMK6f39cX13PZzuwCQwn6HPPrzc/yMbsYdDu3EO8E9pTcvf9BeWCc3fXhi7pZy/MEnS6o6Oa5KTjidCihwa2TB9s1YQLXZRCgAQEm2/tDuv8fbxfkZlcVQb5V0y+rDpE0b17DTUHH6s6P17xfDLN5FxvC3/ziuGDZIskZ0txpkwd0tFr/KkYJ33Ppb2QOT+CiWhjI8F7v9U9aw7OMcEy+zh3i/O+EqGYIa0MA4Q4tpg66RvD16kztzVeAbRxGTkSpPq6cYm2tX48O0Nusim2LX9ZpClpgQqbEhj1QbKMxhvrK43CI7F37l+vDrvlCuF/0adloRdaDF0I0I5L9jp3YxOGNIbQ0WLVif4Pgf7hG+qSlyXvN/hUiEP7tPFl3ilZ9N6Y6aoSb3IkUr2Be42VWqOl+diEsVAk3vzgJ49J336YIoFrSG/aGqY3S8BwoygywTSYDD1Zr/qlMx2i7ZPjQqX+04JL1HxpJvtIJUbH9nPuYxStsCaJ4IwXF7avU2iJV1rELNlG5aSgitkukIIwIqVa4tHCNirr07Q8LGUtg==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgDPHC+Q0GFaG9Jz3CI4GnpnaoHs2XEa/fXlHLqUdPnHQ42z4K9vUOhO2ZQuL2ykyWjvN/KEhmPQKxhJxH1Gr0cTVfn7LgmLTwR1Odfwjs9bxfzHk8Vw4pbx2XhsWPgPWqoZEj76OexqTkx9/H62gmqUAFa74RZRsuoS5nghZya/fq90OrCSnUr4MoClWmunNDysoscCBN2IRRET4fA2Bz1BV7T/M8C1awiO0AXUXVLknDbR96GiwPJK2yFduhR0CqptMg4eAgkWx4e9frEGtzZcl8XD0pVIRjjpPcyEaVpYJGl3W6+qW0Cg9wZ1a9SBY/nPmG+2qECFSDOa61PzA3dGSMWPSXYZROIaLEJ00ZXc2xvoPHlj8Iop7/8OM9tw/iC8jE89WMqE7zOklA/aNWPjAS4CSli0AHZvZUTwdO+eJwuvdtfcCLfrPmSGdUAR1ZbOxwjncY9n++ldvo5GP5HxNnChEwyNMR9R+XHIE7WrtjQ37FVn/oiEq3sxSlOClBmXmrLn4FoIpPQNyzJJhayTmd01FRvRCNjmdqjHTcr8O0Y5dKuqtpF0s6lopigDaWQzZwEuBqx/gjSKnuoMOVN2RsTyAmdq4vAIKv2DaQk4lii3wRswJ0eIaQvmcH4+UDD4icICUucgT9EiGOhCeU9PWX5cbIUZ3GtVA4AvcUV6pR9AXqggw3jcUJl0qdppEOUhHf418KEMqcNqxIzYYezohR9RmYLLN3LLT3QDbW9JX5no+sA=
  template:
    metadata:
      name: volsync-restic-secret
      namespace: mealie
