---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    api-token: AgAbgZNVyVUWId1adKgaHylwJJiOU4wsGs8pGk+DUwMMmOaZITypipanxGIebhkmEOeW/j/aopRrlulcgTnw6t2THnIu4wrWvK4cdcyQyM/ZnlP38YX0WPyyaeo3v+xNqyvaogyef3RKmAvrpM6KdxtJ6BXv09EfGOabf0Lj+tZRrABX2EwQ2TsQ0WSu22BFOzfPEqxOAykdZs4bnJZyS6yqu/wWn/kq3DCB+8UC8DoKtt8kuAm4SN/5rteaOfa5a/XP6MzYDdv9ujXMQ6uSAiooKM09HGSb9X0ZdiwfqX7Qw0l9y0TH6oZDgY6r4ejSE4blylgbnARvXenXmkp+PjVXMStejnFrKbYU5Iw0KuXCZpZL5KG4GCBvs4y3dwMLzdHUvt2Djd7zVW0s7EuB01sk17R9nvw8SE4wD/dUMpb8gqJQfU0hQpWA/73RwDVBDOpc/DMHFOdb6juGst/fabBsBb6vJgsGGYdnLrIKvfS15+tG8HHw/hq2IS2b7M8y8SF1b3SRtErSeZcib5gcqTWzixVM2ghKPUImcF4U8urwa5lZM7TryszRnMtfNki/qJ0A8xUutp0hwu/rjk/NIZYaZLSSgvowQFlE7ETVQLvoJ9LOTRYX1JHCJ+cAEfOxAbUOrMUz1DAO3dJvjnYoOIY4Y7EeB6hc4eoiNbSiqIwTHFdD4GzCkSSwfrQz8vuHm1YWcZ/vQJ081hb3q40aq4uSHZ1dklVCeM8HcLtiDVy/1Q4VNmg1WH3z8AmnV4zlkHcmIUGtfQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
