---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s
  namespace: traefik
spec:
  secretName: wildcard-k8s-tls
  dnsNames:
    - "*.k8s.kecskemethy.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
