---
- name: Install email server packages
  ansible.builtin.package:
    name: "{{ email_apt_packages }}"
    state: present
  become: true

- name: Configure certbot TLS certificate
  ansible.builtin.import_tasks: certbot.yml

- name: Configure Postfix
  ansible.builtin.import_tasks: postfix.yml

- name: Configure Dovecot
  ansible.builtin.import_tasks: dovecot.yml

- name: Configure Rspamd
  ansible.builtin.import_tasks: rspamd.yml

- name: Configure OpenDMARC
  ansible.builtin.import_tasks: opendmarc.yml
