---
- name: Deploy Postfix main.cf
  ansible.builtin.template:
    src: postfix-main.cf.j2
    dest: "{{ postfix_config_dir }}/main.cf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload postfix
  tags:
    - postfix

- name: Deploy Postfix master.cf
  ansible.builtin.template:
    src: postfix-master.cf.j2
    dest: "{{ postfix_config_dir }}/master.cf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload postfix
  tags:
    - postfix

- name: Deploy virtual address map
  ansible.builtin.template:
    src: postfix-virtual.j2
    dest: "{{ postfix_config_dir }}/virtual"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Rebuild virtual db
    - Reload postfix
  tags:
    - postfix

- name: Deploy /etc/aliases
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Rebuild aliases db
  tags:
    - postfix

- name: Ensure postfix is enabled and running
  ansible.builtin.systemd:
    name: postfix
    enabled: true
    state: started
  become: true
  tags:
    - postfix
