---
- name: Add ansible group hosts into /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }}.{{ domain_name }} {{ item }}.localdomain {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined and ansible_system == 'Linux'
  with_items: "{{ groups.kube + ['api.k8s'] }}"
  become: true
  tags:
    - hosts
    - configure-etc-hosts

- name: Add extra static hosts into /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.ip }}\\s+{{ item.name }}$"
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  loop: "{{ extra_hosts | default([]) }}"
  when: ansible_system == 'Linux'
  become: true
  tags:
    - hosts
    - configure-etc-hosts
