---
install_base_packages: true
install_brew_base_packages: true

brew_base_packages:
  - ffmpeg
  - fzf
  - gcc
  - git-delta
  - go-task
  - just
  - oh-my-posh
  - pre-commit
  - python@3.12
  - uv
  - yq
