---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    credentials.json: AgAwsm2TSrY6/FP6kMVRobg5j0Rjx/JNT2GTN6BajULGUWLWt/r4ZcwLD/XCX3k4AhDw5byT0OOp3GTz9aX0FKVJSBCmH7/TAEIbovil4tUEeI9Cu3yCmZeAcXGgMgNvp4muPddIapSJ04tG2PXtwPlKrJswY0XqeOQrXBu6Rdj3VR22tBnsy5koWTpz262ULmwNyk6sLmZvC539O0ipHynbfjc52R6S7vfSERRMRIvaFAteHkDe/4oByzywuW9TXjVJh50kRMjd8qM11Htxcuw+4TOh9vd+k1LzjBYj6DRsh/iZHxSWAokNDIYk41cu+yZH5hTJpEnnrk7nsJTFBdBHzoH709hR6dP8qs4yb0iJ+LGr7K/STX6Naj5RATqV1XeIKabDUfzp5PsPZt+XTXsbYRBTL2CQrh7MzJRi9hVJPE2s9nhfp6S/xhJqsfUBXqV+RnFXXFZzKQuL+5jiclNUGQlvKGaRg/xrkhQbsRIMB44lVNrzvsyqdkfJgIKdjWPIlp7+fc/gvrwv2iRdFCrqb3Ilm3PpPBof+H9K3ys3/8wvUuwYSDw03tJmGukR7TfVv99dzoQO3S+UOSo0pTjRyaqRMRTY3pbJur5fU6n+AnO9fg4+APsThNy5LFcoAiy/C6NVDXG6soeVJ+oS8RIU0kLt7uVF837nTVxNItpXG5ZJjpLdRg6eKAwiouoyQ8qgk75Z9To+McaophU8m+1KdRzb45AdnN26Rg8Dw5G1W/B36iL/8DFNmnZ7B/H/vVVEWOHCc7XINxWWFnrK24lhEb2TeoJ+WH9xMnJA5VQvLBUu+xMKyYSooZeCY9nP01ZRzGJ1Zh2buu9KMlAOzzYGEd8tjtknjhPVUGXgzToyqrzji3RwY7oqEE49t5Llr8RfUFk7yrIxNTRqP1qoWAqV6rUcI+UuyIPUwH1w2jyc
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflared
