---
- name: Apply cert-manager ClusterIssuer
  ansible.builtin.template:
    src: cluster-issuer.yaml.j2
    dest: /tmp/cluster-issuer.yaml
    mode: '0600'
  delegate_to: localhost
  become: false

- name: Apply cert-manager ClusterIssuer to cluster
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/cluster-issuer.yaml
  environment:
    KUBECONFIG: "{{ argocd_apps_kubeconfig | replace('~', ansible_env.HOME) }}"
  delegate_to: localhost
  run_once: true
  become: false
  changed_when: true
  tags: argocd-apps

- name: Apply ArgoCD root Application
  ansible.builtin.command:
    cmd: >-
      kubectl apply -f
      {{ playbook_dir }}/../kube-gitops/{{ argocd_apps_cluster_type }}/root.yaml
  environment:
    KUBECONFIG: "{{ argocd_apps_kubeconfig | replace('~', ansible_env.HOME) }}"
  delegate_to: localhost
  run_once: true
  become: false
  register: kubectl_apply
  changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
  when: argocd_apps_enabled
  tags: argocd-apps
