---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-alert-email
  namespace: gatus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: gatus-alert-email
  data:
    - secretKey: email
      remoteRef:
        key: k8s/gatus/alert-email
        property: email
