---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-ntfy-token
  namespace: gatus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: gatus-ntfy-token
  data:
    - secretKey: token
      remoteRef:
        key: k8s/gatus/ntfy-token
        property: token
