---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: gatus
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgA0NIbCGTxjUKEAP5tYqb8BcYGkps/IszwjB8xl2PRhy3zJrKM6gh5MpNqXjJSibiR1rBQ6Th8bVXVrMJBENlnJ//LybsXr7NGKlTkc4KIcVs1C+Cqzikv6ugyJV0OijWZ92tL3k0oR/JspaTN7WatIPkMNrjoLJa96bxKwXWDuqcvgCtMkP/CxRbyVq9Dtbn08PdATqZJVmk1OTKtwam/iNxcQp/OvTyJ1dNJuRqWyq3JtiMxmK7H21unRGiNcWN5pWCG23crK0bTscD8NnKoAxiCnawgV7IVCg7l7yAquH7ZlFOSjOaR9ZySjfquLWG9QRxFVf+Et1ju02ywF7Vdt+79Lbv7fmW+0AgB3q+aITTQWzlK0h2JAc6oYRG9V30pUmxh9ArM5mX+2mG24MIGxKbOC5V3AIRpmnHJnoBkzl012IHYR4qt0wmp5eC9P/vSQ8uDOYjkgDoDUgXOvZo4bQURabHiIzE7Qq0h3ZMw9lsf3VvwSFLpC0XACWTMnoFGf+GIdksIMWnUd303fv3IktPt+xn1ptL0qqJIoLHXOJr+Xt7rwagbyAYRu2WBQMjQkfhgZPaLOcH+9tBbH/C9mUsFbvS9rEPExKVTVGAtCES9KZHDy+tj7vMXAoMeLh+P238McTgELX21G87WPePT48yd1NbuHsl45tMA+s0Sk0RIGUrCs0I3YlFU2YeMAjr1BQJ4ECIGEgHd0XoRzbmZQ9O7uZM00pGS0PqHYrMMT2GBgNUp1yT3SavpV6g==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgCFYeTeuktw7uwmzKS7Bspt1VO/G24P2BHKujJrng5L/6SMqm5OOJE6Gn+rmf75yJTKgo9fSCc8BvmqIrYNquTU5uwFBk8LOgM8ZQvGKY+bHYk0UJH4EqKRGkI5jC83tp99uNKHM+A3N50czw8ncCBl6rXOjrwM2TF/mTzh/w5F07l0wOxa8/YhSye4B4QI29vP3OSFEBU2tSfVwPLg7Ph0Ch9wXAM2p9hen7sbXGHu4AcAblJIJSuuzcHOi1kIMHjmtSIYn79fHD+fi/6N2yKqlvWhJaTH4ImOTWysVScDTFvGZayRzLrrFXcqe6PH6Sso+oEWDH1TSuZUrKuM7qM/ID1FDlfuVW2eZhv+a17RD/cUICWa3y3QXbjsjKngMMdZ3/OYPmooJc57ef+oRtfjGyjXisA+SDqKSPNENup+CrPOOKA0tvflI4REisJrRKHV3nLYu4+jaKAIc3QG3ngHOFXmtu5hWGIyJUkrMOwf9gDD2hccy9Fl+Ql3lYXgLBN+/9Oh+cz+4vggikm1pAYy161+hjq4bYEVKFxi64fKzoKPrhPBmRs9O27nHMWJqZtK3cmd7A96RXZeMhdynbMTY61yaMvyyZd9FptY2YFbkPvm8bycc6jtSYYxLyy8QtJkSv5mYosvfVg+aZ0VSB/KHbaL0DS6G9lMnkpCSUAjogVTp2MIVT66SATMOz80ZPWdXUxM5wS0PYEaCHgsOVFYA75QgbJxPcYH983tu9RFVgRhpQ==
  template:
    metadata:
      name: volsync-restic-secret
      namespace: gatus
