---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: gatus
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgBPvzLFYpg9r0AT4RfaD46kxZiWePofuZa+Ua2KyNq8dFB0QBXMCV8nYkAbhPxLRyVbiUlrKhEuHt9PwfpnSDZeNJehyosFvi7uOaWbdaakX8SlN/D33sVI9ZPO8hO+zGqcQMCfpW55KEmUND8nvR6QThdvV/OCn3DQ1DqaJUTYPWBIPk0O/1Jm/mKLY9cTO9raDYIHumflPJIFPypmVwGEipO4ovPhMOuSO6bBGMLDu4ngEYtCO2mtyzD7VVvvg9um83j9nrwRxPFcH8m9bawDRg75UFnFQg4bCSU9HWf2Jimb+mBpWVraHDZqVwzyGXbEp/Ldnr5xitLrY5L8NrfF5fXAQLdlB3af2AaP3RT0aE9zaRF+TNXf49G9EUK5Z/Rfr71Ukpf849b/rCVMFHNYnfxR25or5Qj/m1d8/n2wvjP6mUvUjNkjl4wReqy2mbj6z9pcIYvEjip3cxk4KcNjxV4V4TLQ7/0SL2T94W/m7Q26LEfVu+85iDBJS6ypUgkJI6Poy24UbDkuSat+uSB0bQ2JnGrbfKMMcPrMQJYG5gdqYplTsOQC/QZfhH0PTO9HVmsXa1Qwn4yuEOG8eMfbQchtHPbrjrpIkH1GmgS7WBT7CL1EfeefSDcIWzQ2kzCKOL6kJ7NLeiAGW+Immu9d2FGVJCeo+KsPqF/5FIzzSBMp9sfHCSY6omBV318LFs/ECnLJGCXQBw/peqvw0lNUoDAGYOwiD3iQrLiDYBZfI+f0XACf75VFC89vzw==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgBCFdGLRK+31kc74lUMZn7vW+UwY6bRzE/KQjlkPvNW8deywun3fzWc5zzjtbOtUj8ZFsSc4d8SI/1kSNfANp147E0nFE9dNyOEsZjsNYfbgkSBNSJaTo30MtXttV6/yXsj3gHZ45Y6a3RopjRF+H9VxGacJQTlqKWgJKJd1d2w1hn8P379jrWMSshu8lm3KNdBSll9Us65LKJlZfGwZQWAm8SGHFMeiBe41iddqXRo4802Je/1zwknchNwMlaOz7DDYRJoqo5QPNTaOv5t/3rAbLXS6IGvkpRWm8g+BtC27Xv7ayKpoVRuOo4k7rdDY/WsZ57NQBZJ23Cwk6IjupXpHllNaQkkNQykZM3vzSkIBu9GRb5DjKFw5cA3xQ1pqIWsf2jcBIgWKasKOI+0hGZDqupcQQCUrb+uWFXCT7YQ8+1DEeA81fhu//x1RkCqVn8gPBDgoU1A9FpQ84sjFXPBlYJB47WPbieDqlob3AogGVy2paPIuHUBVb2ZvzrggitZt23KskjH2Y0FJRq1X+4ZflEI+2wP3xuerGnv33hTXkau02GY/7DTFXwd5ufE6JJm4yR14rgMTUHnNZiJGKZzCj3OM6vh8oQ2ldS/1nkf0z7usPiGaAulGevKmHrcG5ThR3MYppY/dEb/SVQKk1LjpOGvpVY+hv/vxXiCqCluj68d+7Wb14F4NcxE9AImb0mO3inH0272kBa27qj2sIFKAsRrML5eLBDjXzwE6Feb12eyQ==
  template:
    metadata:
      name: volsync-restic-secret
      namespace: gatus
