---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: gatus
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgDZqvIC9PF3ObaWeeZV9uVFst+38aAJpHwSAlEhR6o+xqbDS1fzpQKbE85AQfxPKFWjI+UFMJXnEjuvQr9ea/879IqBd8Z2B9WVgoHUFrVKwl9mT5JaGYFvPCoFsltizWKR3ju6fIHzq5mgLCIvNAEwljK+XDIIidBSN37bqSX81z0lri5l+K1jviTHbbu9GgFgBxfE0HXdHoxxdlvRQf43JMUza9TWCcFzT21OigowhAtEUG6q41tjg7l5aLS9PaKYiAdQ+qiIA9kp/rz9dmMVwvb3/CPULMxHnFCjdKAnk0AkhIbF2ONLo9mcpSr/Asv6SkAHWcVhGgs4wm5vnsMMm1WdSZMU54DIsdpUF/RqDqmiwuO3YI5VwFJ46ROtDf5nvgUCbedeOmv8H0t5um6GyrjXrC+t1XYwPiHSA+/fwc2mT0HjqjPYYGqy4+8VX+GuLOq1YF1aPfJWAmRlyRyC55cAl5d3yPklz33f+vrcd1CVB/xMYNvANfNWW8n6SqilSt3oTKsCyWmKysesFzNL6ilsQkPBPcT4mL3J0dsKgGPl9S/I1KCNYkZiCu2f4PO7NtZFtWwXTlBXhOQP5y+TmUlXDEq3fHsqeP7aZYEeTgwThlXY7+wny/oItbtBiU4uVG06QhF3DGv1f5kY7C6lR5B1bzsUMvGiA3USsT5K1mfrD1bQ2XE+QuC1+qx1GOIiw5MYwCAdNLmX91SAw7fEVviN2ktfaDLpuMdaNGVwHaNHaNqmF3x0fA9vxA==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgAvGE7H0crszCljOe1/bJYznQoQMvjj6F4vPZgbm0bzUGwvFEck8s8sn9Q3gGYvxRa+qYWV3T4PrxMf6myaWaNXDG4vlv6+YQmDv12zpjcCV8GwX1fJJuPgmzNRzRTNW7MqriEwB3xY9hLnPRwDjQUjA5/VJRVW/uyCsWtX6I00+qARh1h997O/Fa8GGUPap4PlH8EnZcpDsL4pfdaT1hFGeZMQ1Ydms73T7KupOoi8D9Y5YBlR/KyfK8Q02Q0Eo+XvNLczPn7oC5EnAmo6geRpPaWO0K7kGUw1pQ70h+K7zO3tO5qbRhyjfWR+2OI71GRybsim/sASQPjap7XJpRZAbybzMsV9Ev74rLPLHE41+7fB0GI5Xo9445TrXAci1WVVtZmxpkcRCOXrygE8PRLSncsv1JDMbp4pxFrhKvv4X4pS9CF2k9bkitdzZ9HcP8FEJ5S0VztY9+R7oKfRTQKLGTjlF0SgV8mVyzwcOF7bVPEX6qY3eWOoYvqIj+57D2GPKKts0K0uFBwUPKErknbWcfZoTDPBQVpqa4+OLRYrc+ehSNLJk+mxwbVB9b6eqtvBh84YnJ3T+Q0v4QNR7QR9qU6mIa75gzt0rDXXPfds0nPsxG0lQ21su+jvMjkT6aZviFCICaVitdjXamh2QQPl1Kyij5skzgnCY2YR6h0jiTszF4iBVBsvqifSv9JiLpLMyUb4DQiP1vNYzPnE3x/YFZwbczBZOBGHVhqdBralVy6W1A==
  template:
    metadata:
      name: volsync-restic-secret
      namespace: gatus
