---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-ntfy-token
  namespace: gatus
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    token: AgBtkfE6UuyyQkfE+JVJ59U4q+4exlZKctkxKH/0kuGygd+Qic+vlYXVvxNDdVB8s1p1MqFBuHEQ54mvDU6OSGEzZW0FKx31n8Op2jrqG9sKAXsayDDZyE6NA2UG7Z2sM7Hc2W208R9AMHV6zKM9CHM9NTj09g3VFHIO1C8CH8kb6pysWWWrNiUwUJuTwWLqJifJVKHI8scAnPTl6WPsZx7oRrLb/sBzMUM46lSKdr51Nb5IoVo5QD14D/CpQskTTrLdIe2yN7NhZh/HHD/aWofseSZ7B9lu7/b+eHTusGHdXDD4xvngvLmvGYBjWTn0OuWX6zZWBA774QBwLH1shKU1HkrGaZTYGajbT3QEbSjuAfwgCB+d8/k52sLqWfJXbWjPNi3SF2/CrirSB0iT7wEjwsmT0RihZKaMDoK36J0beKEFksTnMx00IRmkgsObYZS5cJdWTouLyM+fjZnTBQTVTLju/Baq7KR60Z8mzkbqN/kDMGRjgqXzMKbxNrLBau/juojpvpn+ogOKGzzPEDHMceqE4AMA3qWQcJ09LzL+XbY2NsJ2HN1BKkDtyJWyZw+sT7on4KYT9W0wy5OKLv6/r0PfgHXSSb4rS5ft4ERe4NsGWsW6F9iBrtISmbGWMCMo/GPNYVAem574n8+MpnTfpLoHJ+aEynX8K7JujTkCoapdlt0rBthJn3yp7yEb1LalvrquJvHYBzDNwQMtQVtMqYU4YcJoSRBFAd4yeeQjjQ==
  template:
    metadata:
      name: gatus-ntfy-token
      namespace: gatus
