---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-alert-email
  namespace: gatus
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    email: AgBFNsq13y8x3sKh6DMKCBvKA0lfJlfIf2EZ26IFLjqbzpCM5AZr5smMLMVxfQv2P0YNsB414G+LCdxZIhkmhoaX8Jkq5sdhH5P4/RA7iReIqCBWFsPtBHyImLLTAkFDWeQ/b4L7QWclja8uRvw9zpSUvliB5eM809tCvxir67Z/V+t6HjfkZJzjiMMhZHgXtiDywbya/37nbCIgM15XgZioQwN8MsxzfzwiGd4erLrv5t9jKyZHdPwJ4mF3NSY+rLaOsydLSTVZbFLNlR7WuzGpsYYDRKY5KePux6paJgl3aLdM262OAmCIcJjeAEyrrp6CvWXdMFgoE97c/RUpkikAt5BQWh+N6+s66WFLRxkj0zHCSSVGUqqnsINKAtyhZsuyA8ly4kr/HneURZhmucSC/Z7gMh74NU8MUfnN4gXSqYiSWHED7zVg4J2EQ9KDpFhWIQsquS7F47Qm1+qkWv0XP4CZb78Q+65BUH9ZzFmRThQ9eAjLAs85u+DTjvxmKQeSBLWs86tQLW4+5eYmEJAgbjfUv/Z79mZ4CIUkzj5cnUJHoy9y4NozfVyz1fDcLaNDLkSoKezZvwATkjhhF8dkPrB+8Vj2/Cxdh4h9T4f9vjCb0w7SqSFcveKTBgNyErHgVkwAcICwbup59oNM12ABH0QOAl/0LwGtKTTZupvOCwYPW420js2JNH1dxkO3wJKlP7Mjicriz5qCLpXMsfRcnftJDmg=
  template:
    metadata:
      name: gatus-alert-email
      namespace: gatus
