---
- name: Reload postfix
  ansible.builtin.systemd:
    name: postfix
    state: reloaded
  become: true

- name: Reload dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: reloaded
  become: true

- name: Reload rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: reloaded
  become: true

- name: Reload opendmarc
  ansible.builtin.systemd:
    name: opendmarc
    state: reloaded
  become: true

- name: Rebuild virtual db
  ansible.builtin.command:
    cmd: postmap {{ postfix_config_dir }}/virtual
  become: true
  changed_when: true

- name: Rebuild aliases db
  ansible.builtin.command:
    cmd: newaliases
  become: true
  changed_when: true

- name: Rebuild helo_access db
  ansible.builtin.command:
    cmd: postmap {{ postfix_config_dir }}/helo_access
  become: true
  changed_when: true
