---
- name: Reload postfix
  ansible.builtin.systemd:
    name: postfix
    state: reloaded
  become: true

- name: Reload dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: reloaded
  become: true

- name: Reload rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: reloaded
  become: true

- name: Reload opendmarc
  ansible.builtin.systemd:
    name: opendmarc
    state: reloaded
  become: true

- name: Rebuild vmailbox db
  ansible.builtin.command:
    cmd: postmap {{ postfix_config_dir }}/vmailbox
  become: true
  changed_when: true
