---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docmost-app
  namespace: docmost
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    APP_SECRET: AgAQm67EqzzL33RMCKwQnIPlKMD5Xx1P3txq52ffdcWqJQJV2ZfFDqCK6z7N6HNiV7+EmnGKK9Nln9rdjCi9gl7hvC/VaDzE/JFlNIOVKfgTKtY/GdjhpTjBkxzhjBpIQxErLXVQC6e5AcNfajr0ro9JckgFkBfImiohEeDXLvYtgeBJRIRUwDf1qcAp3+hJbQe0Xk7rfHnSHeRNClP9D/7WmTlU9KIf3bSr7YLURxcOu2iKyhtZP0NjX4trlUA5CanM4MoSnAKXwW4G0ZL1Uo4G1bf5p9/oMpIMhnk7KEovcr8lBe3ueHywjuICvmrOjpTm/uQmk+PO06gHHdlXHlpgpEcfPfNWywp4hlvvdxbBnPtkErBgCySdv+MVGfpxOFFa/ix7wT7AF7bMQciMASzTyAkAsMR3dAMf0R9jfKs1NjjAtrMyzCEHWaNthdDxdfDemShNdSJzExds6nRNMG90dOs7JJCuUprPCnJCHuqI10hOAq+C44qA/BDmL8vDCasTMqu7AUDhnfu1nn/6zFK0zrbSkxY2m2VaBTwIT6zG0iGZ1LZMSdU9AGJfXjTMJgB+x7K/6QgPG8Clg9bVy0AJpRJJxSUhBOb/GCW6eCJ8Rx+R+bklkt1jPF643AwjXQbyn4+/MfWBbfKn1ZwE7/ofx80KsBMTBw8jOFQNCYLtKWHspKpu6cL3+YgBbmFhXGV7JP8f8UL+/Vhv12eWWDvhsolT76cmgG9LitzIKHwZrd2SMtf1Qf8dEulgK7OkENsL0Vq3whMC3lZ0krZ/WHRf
    # yamllint disable-line rule:line-length
    DATABASE_URL: AgAIVglJkS6Zz+tMIdqVvXqZw+qHSwF84AVLYF/Mg3YKSMPHk8SR1lDSoSmFSGDa10yk022POCPEe4BNZYOfs5c82aQ8oePudckB18OJeAXzgljKRu6PIUJy4WQGB/4PpMS8MWZhkzJhlLwQosgH041KVy5aqU5hSrumpuFzsaCseNPTQWMVRFKpmsK1spKUy/JSJ05+y+TBcbfPbptcrK0513OV7JolxMc+NqrcWis9lMQ/1Jjbkflsh5RTXb47A1DfUFbf1bE3PjYJzGkYroIafB7FeMw6qRlMVHTkekmfBJ44nmcvIGRNjN24RgvtzkJlOtf24zf8l/Vjigo/RRNPxzx2XxC4aplIs3ZzVNSJ9+llXgPkrDwEu4yEtncmH8TwYFc2UcdhxUiLC7uimo1XKsPLzkdLB4ekzcJ6UvxgW1mNI4eeF8sqOoId4gZ8uCvDXFpE6NPyh2KEdB63QRsKJNZtkxl9ch8OyfljgsPn4h3e8fkPBl0uENN9K5jI0d4j85XYyAZorHDQO/jobJstORmtP5f5C1AzDjP8jS+KdsK+EMnaL++OiZ41Mcg4pHFapWGUafvJ6f3BjnpUUGDp3yt5Oe3DS64Cj08NY+qDwltzWEcu+Jefw8yxIV4sInuAhTyEdezvwKDTHNszIPV0pHxkoEmKw6e0kSfM8DssicyFP1wviAgpY+u0iZDXPxQlIdJCqzJoDZurrf03YQ6lVLwQiUuStP8YlWvsxkD4ynKdxTVLvyJyj2ZJ5rqdALVT2huDl3aE/Bs6yXr+o1y2gd/vnix4NirM4Pt1YOCLAq1s2JG4yawaiP7rW94MunihJFavB0UJ+Q==
  template:
    metadata:
      name: docmost-app
      namespace: docmost
