---
email_apt_packages:
  - postfix
  - postfix-pcre
  - dovecot-core
  - dovecot-imapd
  - dovecot-lmtpd
  - rspamd
  - opendmarc
  - certbot
  - python3-certbot-dns-route53

postfix_config_dir: /etc/postfix
dovecot_config_dir: /etc/dovecot
certbot_cert_dir: /etc/letsencrypt/live
