---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-pull-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: forgejo-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: k8s/backstage/pull-secret
        property: dockerconfigjson
