---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-app
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: backstage-app
  data:
    - secretKey: AUTH_OIDC_CLIENT_SECRET
      remoteRef:
        key: k8s/oauth2/backstage
        property: client-secret
    - secretKey: AUTH_SESSION_SECRET
      remoteRef:
        key: k8s/backstage/session-secret
        property: value
    - secretKey: POSTGRES_USER
      remoteRef:
        key: k8s/db/backstage
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: k8s/db/backstage
        property: password
