---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-pull-secret
  namespace: backstage
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    .dockerconfigjson: AgBI+nR5yOZRb1Rr9GPby2AAoLJzhAVrOyd5vEc/tl9t/5G7+EyFo93Cae/seEXLtpXBQDwGTfTq7T9Xf1XtVDma4DG4RW6qUKYCm5YZFfchrWPYRZmmn3qFVOoDBc94IJmjv4AavMJNCNEFqY78lzHAyAMwxeGYNb8j797T79eITwwI8IQDnFY62ovcOeqgpcNVbL0UkxQbmze6GRNbmi95WSf6OCy2M6QcQ9nk6s4hZq8lyO+mG/fxL1It3ey0nHkgmTlt3htUYCD+PXSqLj2gtBofS8vsVhzrkqSk41MaASBw4X/+eJhnmwJs+IuVmQ9dkLmGRzG4lWRN9wamHVTAqluHts59GHmrmg8HxGFq3DNFazMII5BQsnuv+HzYTDUzph8O2NnXv1Zyw9xG1RA1E5i89CmkxYQvGobfBdlD5pBbTvVhkEKCEN3fwmT0giUJrzbWFJxFZvZRxLyxzlhhNnPadjE4MI56SRRVAO8bsUdv6AMnNtcbMCV97xesy7ItGIJ1fXHmljE/s1CHFbNvmh0nEZ1nGpr4xsSmE8F+x98GRSMX/0dpL2yEHN+v1KAmwCS7YoMyQ8D7aLcK6EjQATK7rx/9mOOiud5yjvEMyRdM8phsRPgVN84VzDFeIZ79VJU4N06Jz1hQUSI+fqcAC11ZiYhC+4NA4/iQJZ/+hJQddUUUi3R56yEDKx/oPj08241WoHq/kRLXEG/N4GFRW/r6lVV8kWE1ZNBSuV5RtEFBSkQx+oAkAEPTfApOMrnP77jJ7+BXH4BT6RDfMjdYQ1eJXdBYO2hCMQrSacXJfLYEIfH4zn8g6jcM0CWiV38SBm8pUyxNSESMVSOhd6VqcyOnLv4Y2S87raFJ7YRzcWlzUbWWlAHhHhZhkyqk/S6zpDOYaSYPHNfIC+rm8zqfV20SSHyXt93s6pFxyXFqnMTrKz6iGCuTWF0=
  template:
    metadata:
      name: forgejo-pull-secret
      namespace: backstage
    type: kubernetes.io/dockerconfigjson
