# ec2/ — KV v2 mount holding everything currently in secrets.yml that's
# EC2/Ansible-specific (AWS creds, Duo, apache_certs/apache_vhosts, ec2_users,
# mailbox_users). See docs/howtos/vault-secrets-architecture.md.
resource "vault_mount" "ec2" {
  path        = "ec2"
  type        = "kv-v2"
  description = "EC2/Ansible secrets (migrated from secrets.yml)"

  options = {
    version = "2"
    type    = "kv-v2"
  }
}

# Read + list only on ec2/* — bound to the Ansible AppRole. Ansible never
# needs to write secrets, only read them at playbook run time.
resource "vault_policy" "ec2_ansible_read" {
  name = "ec2-ansible-read"

  policy = <<-EOT
    path "ec2/data/*" {
      capabilities = ["read", "list"]
    }
    path "ec2/metadata/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

# Full CRUD on ec2/* for day-to-day `vault kv put/get` work — bound to a
# userpass login, not root.
resource "vault_policy" "ec2_admin" {
  name = "ec2-admin"

  policy = <<-EOT
    path "ec2/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
  EOT
}

# Narrow write-only access for Ansible to back up DKIM key pairs generated by
# rspamd on the mail server. Split public/private paths mirror
# ssh-edge-bootstrap-public/-private: Terraform only ever reads the
# dkim-public/* path (see terraform/aws/main.tf), so the private key never
# lands in Terraform state.
resource "vault_policy" "ec2_dkim_write" {
  name = "ec2-dkim-write"

  policy = <<-EOT
    path "ec2/data/dkim-private/*" {
      capabilities = ["create", "update"]
    }
    path "ec2/data/dkim-public/*" {
      capabilities = ["create", "update"]
    }
  EOT
}

# Machine auth for Ansible.
resource "vault_auth_backend" "approle" {
  type = "approle"
}

resource "vault_approle_auth_backend_role" "ansible" {
  backend        = vault_auth_backend.approle.path
  role_name      = "ansible"
  token_policies = [vault_policy.ec2_ansible_read.name, vault_policy.ec2_dkim_write.name]
}

# Human auth. The auth method itself is Terraform-managed; the actual user +
# password is created manually (a credential, kept out of Terraform per the
# architecture doc's decision to never let Terraform manage secret values) —
# see README.md for the bootstrap command.
resource "vault_auth_backend" "userpass" {
  type = "userpass"
}

# workstation/ — KV v2 mount holding personal/workstation secrets (SSH client
# config + keys, PyPI feed, etc.) migrated from the old ../dotfiles repo. Used
# interactively from whichever machine (WSL2 home, macOS work laptop, EC2 edge
# node) runs the relevant Ansible role — no AppRole needed, reads happen via
# the human's own userpass session. See docs/howtos/vault-secrets-architecture.md.
resource "vault_mount" "workstation" {
  path        = "workstation"
  type        = "kv-v2"
  description = "Workstation/personal secrets (migrated from ../dotfiles)"

  options = {
    version = "2"
    type    = "kv-v2"
  }
}

# Full CRUD on workstation/* for day-to-day `vault kv put/get` work — bound to
# the same userpass login as ec2-admin (see README.md bootstrap step 3).
resource "vault_policy" "workstation_admin" {
  name = "workstation-admin"

  policy = <<-EOT
    path "workstation/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
  EOT
}

# homelab/ — KV v2 mount holding Kubernetes app secrets, migrating off
# SealedSecrets one app at a time. Path convention: homelab/<cluster>/<app>
# (e.g. homelab/k8s/opencloud), so both clusters share one mount instead of
# one per cluster. Piloted with OpenCloud's admin password; see
# docs/howtos/vault-secrets-architecture.md.
resource "vault_mount" "homelab" {
  path        = "homelab"
  type        = "kv-v2"
  description = "Kubernetes app secrets (k8s + k3s), migrating off SealedSecrets"

  options = {
    version = "2"
    type    = "kv-v2"
  }
}

# Read + list only on homelab/* — bound to the External Secrets Operator
# AppRole. ESO never needs to write secrets, only read them at sync time.
resource "vault_policy" "homelab_eso_read" {
  name = "homelab-eso-read"

  policy = <<-EOT
    path "homelab/data/*" {
      capabilities = ["read", "list"]
    }
    path "homelab/metadata/*" {
      capabilities = ["read", "list"]
    }
  EOT
}

# Full CRUD on homelab/* for day-to-day `vault kv put/get` work — bound to the
# same userpass login as ec2-admin/workstation-admin (see README.md bootstrap).
resource "vault_policy" "homelab_admin" {
  name = "homelab-admin"

  policy = <<-EOT
    path "homelab/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
  EOT
}

# Machine auth for External Secrets Operator. Same auth backend type as
# Ansible's AppRole above but a distinct role, since Kubernetes auth method
# isn't viable yet: Vault (on EC2, public) would need a network path back
# into the home-LAN k8s API server for ServiceAccount token validation, which
# doesn't exist without the still-unbuilt configure_wireguard role. AppRole
# needs no such path — ESO just needs its role_id/secret_id, delivered as one
# small SealedSecret per cluster (the one bootstrap secret that can't itself
# move to Vault).
resource "vault_approle_auth_backend_role" "eso" {
  backend        = vault_auth_backend.approle.path
  role_name      = "eso-homelab"
  token_policies = [vault_policy.homelab_eso_read.name]
}
