---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth2-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: grafana-oauth2-secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: k8s/oauth2/grafana
        property: client-secret
