---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth2-secret
  namespace: monitoring
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgB4KBIhds32K4IJZNOaR8fgV6cmgHXKlNyJKNTA1gfRQUdA1Ohl6ffdxTv3/oWaPnW/h0U8bWOgod3SgNO1wAAkP5BQ2+0Obqdt6OV6cgUjt4paJoe+yruFWLhYbPNNY1U60A26Z+AaZyq2bYP9eFDN8ASOFIRfelwp3dbjealexREniOVFbTf1FBmRWSw2HDbHT5JIRxaKNYfZucNv6omA8lcMx8rnJbleuKTXree78OcaG73vM3Dx0CgVRN/vgJ48KoHTfLqoeQCCY/Wkc8KD43wSY2DCvGN7OFtUQgHJ6tNuZnzJ1L3I6CoIOsyTDe4geYuMIpJyNc4gPn51RZRcRBMyBWfaf9uc+lOYx4kbW4t/mfz1G1lmyK73Ef7yQK2jWpd3GyqDdewk1pAVHCc6nQ2AIJDEdYzSwTD9sWZSsgOyg/TB4yYNOGT/EXVZLakzFOtQfn/tgaSMdXhxrIPk+eTesyyqq671W+QGHI3Ns6ihAdg341IgsD2GjuaFIKci5+QxUiez3R4cum/zoaL98nE+YA62lUgPlxZZvyLiKreFhOAskRRl6vhUBWVsYggpSStqNEozJG9KzHCHVtD9L6kCG77khGrrt46v479rnvE1RY56JYMXHzsjs6fAVajjLfGftA2V6jdMhvcJFR3Oeo4xjSLcePm/IS6FStjy0WUpzkm72dYxuHr15C3SGW/GZv0kL5KOfrIiFzq4h+/Y0ax/i7lmrppL53C4Yo+Rb+Bs7H9lRtidW6HS9s0Szk6SC7Lxl+pNiNgBKOy6z5dX
  template:
    metadata:
      name: grafana-oauth2-secret
      namespace: monitoring
