---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-tls
  namespace: mealie
spec:
  secretName: mealie-tls
  dnsNames:
    - "mealie.kecskemethy.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
