---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: backstage
spec:
  secretName: backstage-tls
  dnsNames:
    - "backstage.kecskemethy.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
