---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wikijs-tls
  namespace: wikijs
spec:
  secretName: wikijs-tls
  dnsNames:
    - "wiki.kecskemethy.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
