---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-tls
  namespace: forgejo
spec:
  secretName: forgejo-tls
  dnsNames:
    - "forgejo.kecskemethy.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
