---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kromgo-tls
  namespace: monitoring
spec:
  secretName: kromgo-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - kromgo.kecskemethy.org
