---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus-tls
  namespace: gatus
spec:
  secretName: gatus-tls
  dnsNames:
    - "gatus.<your-domain.tld>"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
