---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance
  namespace: glance
  annotations:
    external-dns.alpha.kubernetes.io/target: "9fa18953-8d82-424d-a8b5-9941940d4230.cfargotunnel.com"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`glance.kecskemethy.org`)
      kind: Rule
      services:
        - name: glance
          port: 80
  tls:
    secretName: glance-tls
