---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: authentik-credentials
  data:
    - secretKey: bootstrap-email
      remoteRef:
        key: k8s/authentik/credentials
        property: bootstrap-email
    - secretKey: bootstrap-password
      remoteRef:
        key: k8s/authentik/credentials
        property: bootstrap-password
    - secretKey: secret-key
      remoteRef:
        key: k8s/authentik/credentials
        property: secret-key
    - secretKey: postgresql-password
      remoteRef:
        key: k8s/db/authentik
        property: password
