---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-grafana-oauth2
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: authentik-grafana-oauth2
  data:
    - secretKey: client-secret
      remoteRef:
        key: k8s/oauth2/grafana
        property: client-secret
