---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-wikijs-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgAg4TEzEfO6w2QM8Nj8IFVkBRgx3BrFkc3MMyB0ZyXr5PCgdYG8w0xNWlJVHI9fbKx66MDixWQx1xoGH2u69JD4Zdj+wQoLKRCoXQteeMBT+QRqxnXDStEEJmfJYKq6nPa13BBIMj49KhCHdVhnxg6dFWSOE5QjfPWo+irGINIjaSjg+9hVCKKWcEjGSO9sj6BcZ6FXEEHA4OHq2HjCNMuX3jMM4e2lu6Xe0x6D+xlF02lbtOvU1QHAfKDSelSqQ9ZsrN1PHKV5Fo0mLHBbFwsoQwQLbvFNL9SBdGuV8bQJXP0xOiPUl+4Mtubq9RZyvxB3OMvBVkMF83KudbaY52AnqBR9Xip46fN/3QQ6h9Le1LxWqzIcncsYlDz5KQa83YYrkjEa86hK05oyFzcGwz7pkCW4UmcI6oAy9KwR7BakIYbIHViUuvn+2JHELDZSBd/V30RJoefHAkRhDroYDZgkrEtWouD8f2t7OahFJ0WR40j4BQeI9RtrwKPglD+rkY9Mo2fa8W06a58nMdSucBGLUk03BpE26NI6AGL79ArcxUIl4FYFb3yZr1/8Imsy9rBzPS0fC0LK4TkXfgM4+zmxnvz0PxxQFG+whyEILhEu/Kk/gBElFTCg2KYrKDeozGelu9qo9BHJ3gnrps4/wZU1gLZRSFt2YeoaTJtzKuLC4zMIMLTjKEQXU27w7c7955Aamat4noA6oqH5kGRwQVoH7pBD9y2XKxZctgqrsL2AuJg+gcuqEUos
  template:
    metadata:
      name: authentik-wikijs-oauth2
      namespace: authentik
