---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-backstage-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgCtlNcuuBc0+TTkhsb1nCdsZkQYrMu/22kMlp6TRcJnR1nAvqrhq27gnLJNuOadkDIkvnZ9WwlKlRZ4XWBq/lqCMJTHirEwTAcER2mIwZ9y8GSwVFwflo3K2EwPla9NFsET8cqJMGetiDtD6B/gaesdKajnO6ICyt8/WKCHBLvRaJ+pwx7EBV+8LaN0L2+czhNQuE67JPwdNEfPgDvKerjzzV0r78AX15aVWuq16hCYH7e32TqBVEMWQ3izHs7Lzbmj2/ZIatZoDUcfjnQQkQakgEg8R2+NX+ZSTD08ednsSrWLjS251B6N/EcgcloTwC6/0xclb63ZcpwNRF0Sdz5fdNM4oyNOz2/LJFw+0AhA+EL+oEjrYGppfgv9MlBUSRubcQGgJN/M3oUv9zcWnXwZVamk0hmfLWjBx9PJPbqOSD9SSmkbljW2rzRiuuUaqcGzqnGM1NmYsk9RWnH1vltwBrRDtHexp0KRowk5Ty4h/fosRY5cJatFF0fuVni/ybxUA0MoM4istr6+fuHOXEIZJ2fQ+bkBr1LGJwnQypOUTim8X1Hla0tDgWVx1AtCnT4n0I0nwEn4c9WKYgwvp3lljAnVSqkC3uVAa7+UXxf2zDIqUQDnM70Mdx9XmeeAUyyuVLiEk9vfuwPboHwpYSfcs2ejX8pEXj3sK0BmCDIUfqkX6BtgkM2rX6HiGYN0+ZI8xvqRcukM18xEMRZxTVvPwhcjYlFYj05Wqq0XPSBOew==
  template:
    metadata:
      name: authentik-backstage-oauth2
      namespace: authentik
