---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-grafana-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgA/gQnnjKhiMAblGk4Q5lDCMiffVxMQpfF9t0wBZk8zaO2LFFC5qQbdeDNIs7pUdgbeh14ADqx/E/Yq4TtYtJ293uXipF7tjGJjQk4RP6CUemO7DSz0WoBJH5F67G7jNlSD1GfVQclHAcQfT+jXcQhyT8C86AcDi6iYddygHkvPgFl9v/SZllAtNvpNwtdCEyBJT+hy7DWfhewYLhgH/lP7XtIBlr4ZpD7di+bKgQpUToYOWa1JN58bkuGvU5wCpn5b6ULXu8f0Pu/S3JilULM3d8EFlse9t09bi0SlaJp4cbvBtANgqJ7JQgSaElXFqf3USSA6iZc2rwlYHRLCTssFPgk0CZSr4cZcu8W4ZbBVV5U/XYGZObyGPUyuclQVzSAlgwln9H2m7O0PdkLdRUhHp/oQuAyqfWcnEl2uE3WjjDKpwoPHl9Zakl+9FxfSNM7Q9AjHQxSJOgL8lEvH9V5DH6Fqv8Rt3W/XlehaPn91GRqiW5U9ZCXjmUtsoHxP/rhNeUraHnun8jtuFiZmzTS0c9/eV1Pc1WY5IWRh2uSMECK4ZwKak7u525OLLMZGPdpFUnZvjOFAhfV0kjFG6Os3fqmxPk07NHBrjGkhmkl8zcovahS9fmXAOgW3iMiITq8R0CZTUU7713Lq8kyO1VTtfkdQtyy/PV9Nd9xZE5fMHl0UgN2WZxLPc+4ldx9RiRX3i46GZfHh27BXwAtn25PVuBMLfQN41/pGEIBdRHrEbJfuV/ddJUw5h/vwwJ+3oW99jC7dB3QEwBHbSkHdOIcJ
  template:
    metadata:
      name: authentik-grafana-oauth2
      namespace: authentik
