---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-argocd-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgCkmr9+EF6je6me+PMmsCPX+uCMqCtH9fPPtqwywZGRrOX0r1HjWddCZ1JDqazpI0OXSObSr8twVXwbgtmI7/cpkB02Efg7WRWrM3GArZaqmB51ukLfyGJueaAG/mNXYe6FC6ELvcDHAlQlyH8je8e4Bl4omvgZn60mjg7Vv2f9//mJphoTImeFYKvTL00NBZcBgFquVpGNOlC4OBoA1Duf7YnoYGnACOGWCt2UNwfsy/Kn/668UMQ0qy5ctV0iIqha9+uqYWUn0dv3xUhf35GOFQjoJEpdUQ5C4ydn9xNsP6N4mFE7cQYGPe76eX8u/4D2HZ05/0pfYj2OZlK7T2NZmYCVLYECYtZuNgMaGOdLagP1EH5Z/O0Yr0rDhjvp3cUacpImesHrTQx0nd0EqjyxnV3BX8QClMyrpbw3w+/VdOiZEaCTRudtnuC2swTo6xFs/xJcYcZ5KJwiNNiOfRz3kqOurilqcIKq6hVSL+qiAwEg/ifh/TPW8GQ9evO4JwM+Wi3nB8o73Ss1kVoyBbEGTyU9YgRtFeyuyA6VSCdEz197oRby0RnwNAdveLk19B5UWwt1ikZTK9hQm9Q0RWZgoRbNbuwj8PqXSsDr8cQfiNugKotIApVk/YxQ78LaBqCMgOXvW+g0H3RceOMVwIUQ0Z98+cIekz9BVWxxRVkAOn+Tg9HB02H5uzFvt8jqkgqbPfMV5lHBGosWSKkgjlfnmNjrfuQUw/ONJDL43bIEQMZieiOa4y4C9AkMYxIgoKCVunm3Ca48FKk6ytrV9pSw
  template:
    metadata:
      name: authentik-argocd-oauth2
      namespace: authentik
