---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-outline-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgAGrBrDjVxqTsSD5h0eHCFoE7FT2/wEJgNIFWpJs/7Q5tmkNce6ed/ewo8/YSUj2CZMmrqYE2UehXGuB7kW9Xz5qulN44iRWiGIrNRVRh5iR8CRk8mslp/SRoTYAar2BFIAuzZVzN1GXZ2p3/XSoaHeU6wQhLUK6KJR1aI2mMbupo1knj9++ErPnOIlBEnJGl4uPVAyYKOqYiU+0tnp8V7Xx32ef9hHX7+tLK6L+pjq4OanQGpVz00NDPBXiwaBFl9OibHFb4PB3m1GwqwMc2VUj2U5jbDQrkvJjDzLxZ9gSR0jG0ovZytaxbJZGO+a4SY4Y/sKcWJRg7cE8jr79eGJpuDA+LlDgXNe66hz/kN8Bh3pWPjh0qJ1z1QqmgeZZZ8mF0+m8UZ7gwavRmmPjIXncLk9WWxifK1dhulN4dmyHho5Ke4Jcg7XYTLJHbnzVqv8cJ6inrGD6hVUOeoup3iVUDA59UDS2gWWzwEwFpYmWPjgM/oCFNeDc+TsB2jMoa6wgmw1ZlRwb1sMaj73W8/rtZFPpPdstShaKHc0Qjbm1v/mOBOhxWD3oDnuHOFAUmA7MNwb0P5xMAq+6kT7hzJSJarsdZYhrIEA3IY3725O/4DNUgmkFKX1Qj78YBITa0etLgynGxYIHD5Kaou9X4p/58ACIY0K+pcqQLujK0hy9jIfMUAX9wP/PK/6m7f0JJIhwmddaiPIVpzZhTQqgbeVWFcxuV1HX/bFKgnqjgHcVMj5kQ4NMBzd7jIetIjLx3cp8QrechbI1uWkNxmpOizF
  template:
    metadata:
      name: authentik-outline-oauth2
      namespace: authentik
