---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-headlamp-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgB0ReB7FmGZjAFUbug48BAv+C8rLgCDwMCN3Pr2A+PhZwlvMe7zRxSeOvTOVgP9v2Bst/OSQeglHSu126fU4hWR2NBi0PlhJW2Og63VaMa35NTypXwJcj88tKf4DgSLSbOJPBub3iRF6vYu85a+SI+XScm1H5jA4p0J6MZgR+iItZYR0pi3PWi/YcJmYNfKaDh+cOML3JxWGaSP9CnN8l+FY8PhRVhCdbYfzDmqOaIt9F+nM7aDM6RBLx8s5LQyzSP075Qvbob4Oa+LZeRZlx75kjf/SCDNTHN8OPZhQhwO1zVT5P9lAz69FI2lJzUfa9iEGB+XpCks5G0QvFwCqKcldvtgqVgaZzrbgYMufEqDxuyQEYA7SMTEMbixtHf9/SGnnV+23ymoCe5GPQlGfN/ArJ3aBJ8yk+veMmK9nfX3t0MtpLrSD0r1w7p/S5aAT4xE7cCvKxHQKalOTNTxcaxNZTWqxo6nMGh7VxO/v2xBqCD9Oodn1q0QIw4otnz89sst8zbd8KAGqQFNAlZZytcqiti3f1JtBhhpn7tqFdTC0VmNi3bupB/xU9s30MKOBnHLTgzL3Ufqlhp0MWXiRQWx9/eayAKczq9SB9Vr06aOaSfje6/w503Ok2NONy6xVeo7VpipEvF6pFSDXwh04ZdMbXoU/DKlKToMpnAnxK2vqHE8jx784/PvQQ+QZAe+ttpBQBxsF6Nda2lv82IkyvgGWxT1NU0+caxLpso+I2hhhA==
  template:
    metadata:
      name: authentik-headlamp-oauth2
      namespace: authentik
