---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-forgejo-oauth2
  namespace: authentik
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    client-secret: AgBg/lG22Fx5DIf6S8bLi6IY2yVuWOeGxvy+cAqWTZvk4jtoNryhY2Uz46YSQMuGxxoSoLdDlZYl0iiH9jFbc7PhcjAyb0uM4EE1FFCs23ELOjwiTuj3bFjuRe++jwTCLc8hLOnaEn7ffB2BrD1mXqE7qB9wR+8AUSCYAdqaE6B+UQXOgmUl2G/s3RbaEhCDoffGJJIxOy8isX311XTJt5C4HH3KRzUjUAng5RAxIx3rfoj0wSYMWhF903hf2KO3Bb+xZCHvoOaEvq7cj7ZWlzPziQ63N67DW8JbA127oDHTZNKc9ItwXeoFEtw5K0lGVXWqgJ6mM08TScCu9KLpfM5yqhAla3F85FKK2E/6zKkDerUdjpTJAXDGZiDxJ3y6oo5gpnWQWZ62xJT46sXkmRLoLBkURtmVml0tSWFayyAAoyaVTz4s6aHtVGsUUMVqUJH7KHCdNpWPsfT5QyIiiZrCaUMzgWryiFSuCK5iR8/D0MwKjgeHHWZL+8UFfOB59o+BfVX+YekjbHdOnL/zCIM8NX20D3ylUN7zxcKZIlHlzopBc/E2qL/lU0AMgJSFBNECsxPpijI0Sar8sTmX+Rahz5PXGZoaQWlKNGTVMhu9cle637Tzfl9MCmwGx5e7yy5HWRKhZ+d7blNiy53yq1bsRDJJMmEY1Sx0zFEBgq1pz1Teuxv8ufjN1DfF7qdOZKue2ZCW2sCsd/8xSWF+5Fp24v0XPy0OZAq2u/DklRo8aZcYBxAXXo8fThM2zw==
  template:
    metadata:
      name: authentik-forgejo-oauth2
      namespace: authentik
