---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://ntfy.kecskemethy.org"
    listen-http: ":80"
    auth-file: /data/user.db
    auth-default-access: deny-all
    cache-file: /data/cache.db
    cache-duration: 12h
    attachment-cache-dir: /data/attachments
    smtp-sender-addr: "smtp.gmail.com:587"
