---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-smtp-email
  namespace: ntfy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: ntfy-smtp-email
  data:
    - secretKey: email
      remoteRef:
        key: k8s/ntfy/smtp-email
        property: email
