---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-smtp-secret
  namespace: ntfy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: ntfy-smtp-secret
  data:
    - secretKey: smtp-password
      remoteRef:
        key: k8s/ntfy/smtp
        property: smtp-password
