---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-alertmanager-token
  namespace: ntfy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: ntfy-alertmanager-token
  data:
    - secretKey: token
      remoteRef:
        key: k8s/ntfy/alertmanager-token
        property: token
