---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: ntfy
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgA9drkYPlMGH41KAdy7gh1spRXo3eHua/kCUQl+hpZ7g3JXZOGSNgdR7uvW2YaDx6yPlWeGLiSu5JufqU/p4BuaHN095+EtQvHMoIElR0tChMKX3O5jaD+4fMQ6QNZqz00fLSxyhvEWyRpAVlq0J6Jycl6enIACdL49yWLUk3Eo+hJV1hW5kotjxUIbRPd14NdKzEU4VnFj1chp7StLtMXaqlw0JxLpR/iz9FDPeS59CPqgmZ4w50cEQW9T6xK98FAKMK9+zcAdjNlbvpreS0aqIqXeFgc9y7xzrkq599/LUHf/YNNtgq17N/gHMjtg2E+oj2QX6zpUffPU1hcvPRmLkLB/NQM8fTJgy1FM1ooOhm7wi2XutHqyXRBmaWFIpjf3gpg8kOvuqOPA9yvABq6g1U4qqVUwEgT1anNx57B6RQ7KxpRq47l8VJ74VA7Y4/rlwsZNtzAikbhXw8w0znKj2L6EubwhTEUrgmr70iohfSO8VFqA7C8NiuOXEI4PZJ3jMCL5mQvI9xwfPUxHSAgMnf9xCqf6VRN2T0Su8JfLuzYAuGKbml4OMT0StrCrUGuuzrSDcmrrtLGI+yi9KllMPy27vhAdRo7D93DPdFR7ug28+/c9y+x58C3rCxb56D3hgbLTDbRz7RMyI72BkC8XqFPrhpebI5kHSUFYMceicUTs684v18A0ia+6e1TT0Vv1YFVaD5bXUHGTfOZ8mhPXXgqP1HsFd9tIvNzBTmDPRc3WqcY7Wsu6pfLs7A==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgBfHGKFJZp7qqCCwMdi2GlHI5ZHjIqMgARvXXguLg/F3CIfyd3VsntxXxELcH3JTNqbmT+RdKiY6ob4vQ4VYFGqxNh1qjQk3I5tH3xE278oLA5+GRTE7ayEOdorg1xTDTWgGnnADHxulHY841/7ZfORJaxGElqph5ZRYzIFim+5imLdCOzovMttHrSpHgEPVDNcGbVmhDcJNW5sWPOVqMdI2xGIuGqDNfsvD3G5i9o7VeeAABjBOHCtNkVwfHUl79zatvCEebUeiZWw3EIEQvqO4nV+Sr/GlVuisBDRvr8tnOr1Gh9dF8kBvL7WqlGy55i9ynTONzezS/DDziPKQX3k5NSxX7v0XqxyYSCJCawAFvxvxQ2ADT6cIRjnHx158QNOJQmeEc9hoY1q0BSJYDjJPwUHMLgrwLtkVcWVUHmBLE+ZGRNi3MDnCujJ7YDTcbcWMGwx7S23yw/7yvMjIQWFD+wdQFs/Y+9sIMJgYLsFVB8AJ5ojVETAM0pl6e6a1JRglG8Mmn99Yfr8TwCe+81elCdVDxNImRBXjlxjjNMjESoo2UskeDD3kIgVCTEDjO6iN2q05pa6Hpg+oIFSTVBuGPPY0tGXV77G2lpbJ4C7vgwI8onzqXCJ30eJNhXTJFKoMNVzppCD7ll40pKZ15T8dQ4RgeMRKXTsplUaMLEtlmclYnP3wFLXGUXDKMTla6L/VnNgOESrdCakUTzRuxQO8QkK+f2dveCgGK9Mck7z1JuT
  template:
    metadata:
      name: volsync-restic-secret
      namespace: ntfy
