---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-smtp-secret
  namespace: ntfy
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    smtp-password: AgB2kqWj6RI1eN48cWlClyjKcYdzRq5RUsQ+uMmX3nmTC9N/ayTa1VVNy7HWgaNj0KOWGNNkzihjP+SANgywZhRtlGXO+B6+Q2LeDfMxl0rW4fEZK023CHFAg6vMz0XZDIBh4Iaa1WU2UomiarXwY+ZAL15upKEHRggUWQZtH0Wtnjc0ynUqU6JQZ8C59+NDa9UCte4IL+osfCBivyYbk15obsRJN+8tDBAMN1P5tzP6z4IslhOwra0Q0OZkCQ1EpVBgAnB5zzuZurQGoI5p7NmvvA/B0ubipdvsAz13A2dCV2SG8WwoQqZ9M/7hSxSwDnc0MCcpYPh04idPe1aljICkP2uzg1VCkapRa3a2Rx+wSMfEPO7FacPVTKxKbVwG2iVop004dH0b9Jh6eMKNJ6y+LsrEWb35ks8g1rm6kTQbzwGI4PV2ZXp1Hi+XiOERLcLpb9JK/umMU3M+f5Q2ZfpS+288rytS6gNdQu/omWKXxnSObaHBixh4u+0Inw8GpbvQgmilV5c2IPCsmtXA31ulFdIOEMANvU2ISmkJ3ieNfHXzWTsoJiUXTIy4p3Bsgkc5gLl4PY0RycOUwExzrYBFm+a4j34/VKS6s6JzoEo7PA9lp5vv+8tqYjdPXLVpMxFJTJBaOxIqYvIHRadWliEYQFZTTjLvQDV6kcCygszqOyFfvPQS3EDz3/cL/jjZLX1AuGuMwKC1etbNyZD9MQufK1ts
  template:
    metadata:
      name: ntfy-smtp-secret
      namespace: ntfy
