---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: ntfy
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgCFBV1JrD1OF27jsXAXOJRPOCFHhQybDCAzZyKXqKpeu6h8JvIoLsFOPv8vAse6hQ2+4enW8wV8lZe9hPdv1/dKAYzBmBzLM0/yZ3a13eHTsvrz73AOngiG4ZvWmBrO47qkjSyuEy2LEhZpQsQ2cW1RSJEd8xlojwojJh8n55CRZJYcgjvApyimsdvAKz84k9w7x18niEIvBk9eq4lEWJ/EDHyYLC4VzlGCZ+V68yRTQsaxq4Rqd9LV5DvvqKfVti4AakYQ1ox48trac/dEHjFHLGrPmj14gjlD6DF7ouHb2jWoYf9GJQb1gj6DAMsOpkhacgeidFpwIcN9m4BDkePWbEs/k1PY71T45TSNFnCNlIfPOwP27i0y7f9OFC6r5vuqv9nj+371/M6j0NNL0vfRypvv6SzMb2qgmuAn/LhKpNtTTi1ocprgmIxRrZq2lWIbfcVFxAqjn7Ti1e/k3T0VmeHPdZfytJoL9f3YEBWaVa1jh79kASvxgotze7yoMuGN7juhp+G2NW9DIeY8zEVVDGh2v3nfmvEMCMSldKRr5dnH1mpMAK1eR9KDgFFGGzIURAvdA7pwATUMpyfEuKD+VnHgVJ8I1+HCu686YG1gtNyD3gXqO39hQJaMNjT+VNyRb5W1nbzFwMY9yC0TkQvJZLqPQZuuO/wGZOWVXtflKT0n8K/hrvapwC2+QWw+oca7q7dn7DfWM5RcmbIAj6fnY9cjsvbk7nXq1zeXr9SCiRouhkVE4Vr9g8XStA==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgA3kvDVV8oWcJXuhNXrs9HgiiivjcqFN4kFiF5tFYLvEAi0ZY6wo3urgNZaall9n1L2hPmf7Rtn69Fsf7z4ZyMZmZ7hDKQF17+M3U7C+GEPI0b0p8lPPdDFoYXWKXxY/AfykkJX7Ngye2jOE3Yz6EWXH+Ld3IujYdj8J9uAw4SagpB+el8vs0FIsSmR4uo3Sg6Q9pkeZJLof2okY+8WruLlpQEedOKdNynjRJsvS9l1q/qyhksAgYy2OzAbUvd2JjILczFcydeD9kXHjjBZ+hjPEB5rcNtxDLYf348BHXcKXuBYBKBRzMJZu+pAx0kE4jX3Em8903s05RnD0vK0+maFcV4okr7dzZPD2D+lbADQ97IRqAm/SWbwZgzOw2rPZMYJA4zywEhui4WSYFs3EonMsAkzIrWrfiHn02J3/z6vSbkmvzYuU/aEeTRoDVxBZbjizsUFBwO/qdRGaDulP+L3RmQrIhDO08R6L+rZIiOk0HD14Herd4QlTyelnYOM2dVktb2NywVM0TotKxDTWoYClrXztVMEgvvryZIr7SAtMxXbETz35iA/RYdbdnFyzHf4ryrxSWui+vPmJVHwdGIJJWowArpacm1d0+TNBRYCSQ52p8wSbNaGBUMePlpP1R7ocIHvv/DOQwZynGFhNySJONp9TuSwiKKakEAZj0lpPwlVL6zuqWFksUhTAOe3i0oyFmb4rFOAcDPHfQ0bjIEoFDRXkRCcbS8rLaWZ1tBngAB8
  template:
    metadata:
      name: volsync-restic-secret
      namespace: ntfy
