---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-smtp-email
  namespace: ntfy
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    email: AgBcK6DrnAWHFn3B2RRxBAGOhsSLPlGT4p7rRVEiGAHyWuh9fQJo+D2HNU3wEcRutL5leCGrSZWLuHZvAeMtj/oYTrR752aTq32ghaFzuEWZwpfAX5j1VApIqSAED2WM3KYm7Ko8McfT86G8onq8ropX0K6t0FZLHGe6sVz61J239y2eEgCd7T+nDv8sBCCtZCMXQWZW91JQjQZXmmciEAFMXm4af7TX2TsMzhSeOX1o4mqNuVjEONzHtBsG1BF3VgizJJcEbbAqlSS+W968ck6bLBtorzjvl2ArOAfuEI/CT0hKiTbQJjqZL51R9CL2tGUpjH4Dr+vd/e51as5thsdED+jRaXYfJrKvtvuf7N0pD1AwQ9wPff7oo4Ww04Q+UW/XbjcC7RsU9Bud48WIqBbkbl8xER5Rjx9dyntJviUTuKqpHOw2zeW1Zi7oRpNqNUdCHJBA8fv/xIgGZE/cd01DbFxk1pd9OHSUuZ3q5k+RK67oGT1phDzbU+UOk16vkaQo9JMzfE/vjyX6HW7qdh2LL7MlLPQ8HKshc4ATQh8OmL9moxh5qw91cXF4TsIgAL+RXAw08IvT9DSUHAmwSDdGJxpyN3VYyO07vhpHB4d4pgGtJaLoy0Efe+ZozmPXPLBbtUhjHYqZSS42rTOkjlXRxhJAd6Tm4AS/4/K9c06BR6VGRXdahTXaEQdjectVoR+bOlIX4J0dl55JIebxThYHNm7yuCI=
  template:
    metadata:
      name: ntfy-smtp-email
      namespace: ntfy
