---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-alertmanager-token
  namespace: ntfy
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    token: AgBMZ7eBXXRm8kBJFclXtXETeHKVLjh79MlAX0aQKLdV49MVLmC7AwlnXTwb8bPO+NHrLh+26whF00sqd0pGZmErqEsv+1mp5FG/CN4okyze4gO/Knu46mIVkPZ77lqOwZdggWTdYzDpblp+j1l1k0lANnujyr+dei4rY2TQ8xHp6ehedXFCDp2h4sXOs5Vmp625sTV1NMhABmkO+qRHPxAFFXnmPbtoQ4YrOs+7NxTPqr+KGc7gw2jhXvnXk6GxGhffEA1gqTS3azEHVZDKCtaJyh7CgJY6bXDQfS/xYIV9lNH7NdpJ/H2L5GjbUb/A3EqBadFGEbnX7V63xSDe1kZLspMA7yqIAO4B/nlq0mCxMufwxl54jsMf+XDMXilFLqby/kpFPaumBbi+39yXlB/aSHvd/7LT1x+jyp2ggWvvt/1txfLPbm5Ev1JNVKrePaySmhLxVD9qd380hdHWxG4c3jdg/cYbeLBU0ZWuP/2Hlqe5rCKPGGWh+9gDPdAlz1SdtrrIs4s5xaoBlHkUKBuAUWrmKHeWL5qm1q6vpu7+bMASs0/0H291PEmeTziOnDyfoTGaTB3hGUr5Hr9uOiOJp9vcIIf5mb3J268sfp/YmJ9z19ZAutr8vMr9ra0CKrzTpoQdJdwEneihyYxR1Hh4LBk9Lxn1UXtlJ8DSY4SalX5woQPZ4jKWtI0/SPnGinPfrdmVAkWyB8Yl2wzgSywAbqvzXdJTMblFZm7q4JmuBQ==
  template:
    metadata:
      name: ntfy-alertmanager-token
      namespace: ntfy
