---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: ntfy
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgBI/wUl/yLUMvA/zYCnK2VAv8ctO0DpHlpGnWliwtpqA+nZuESop5HUyEvf30E0TRGH29HWnIC9oM7NyeJoS1rSjKUuBght5xKLsqXq/xBMyiYrYEJE5JpSbUugjOWO3/S0GzdrSRfSvrTKfj2cVl64LVXGV2iErnkgy4fNonnXFdSwQLv13zD1D/aZ7xr/Uj0F4g1blRggmR8O5q9bsejEy/nI7OQOxdmAiHOSJD4f4aE9LhlyC8HRAYkTooyf/8nmziJrRf2Knjl3+ob6LQjKX6pUxxa+kIAi/E2n6bKrQnt/DuKL/Q3YDuYG/4wb1angJSb2AdTJVz6a2vmxof0Gktxfv1VlhUf3rzId43302agjOnVlb1NgvmNYoiBsifHB1d3BRQ6tetg6O6ob9m/1B8HGkJCz9Ga23I2Gu2nug+svLw6FcZoyefRRysmk+eWiq038QYzx7TkzaGdmnf2Ob0RGwiPwI02csaF9ZMVsMf11qnZ3OkRXp1FCKKChvj6TUabKJoM5/3DalYjEWmaqq66OzZsCJbWHJ892YaTyXwYEtaVSv15jrWxH2kGWVGNCLbypxw+3wjoqhMO3FMua+TafIr4gRhg34fhrPm7A+IcCiZCD76f1TKfxSyalXRQaZigvp9Ulje4rYeR9lOl7eEGX3HXqYKBJ4yu3J9le0jwiKWR8RsVHrIFlJU+5GskfAZIhnviv0nhRgqko+grKTUuSC1AjQ01jda1JbBzv9RgxNZgM8F9m3UkJ0g==
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgA1sG0DFuN7ei2XwXmCP/S7Bmslc2KiteJVvCZ4Pj8fgvcrfYkbh+ZcOqMmha8twwhPta2fnzAt10cRcf+ae3Vy04TbBWB2OtNxR881AeCadvgv5iMpXZHU+/ZduGNHXieBUr7BPqYVjZw3g+jkxeHtZvtlAPPWdZvQhfJcGE8tt5DVDUE5pXe4foTSVN9c4rRr+6TLnXdYG+v7FZDK9lmlPqgoXElGxD2pwWdMZyW6vJLXzK4Jq3lnZ09LM5lofQiR9gqyDvTJcs4m3f7WQLI6Ak811tK3yUei8+tC34ler4DNAkhXsaoM+QwzK1Jywo//H21RS1tzR7pCcb2rJpwG4eD8++WPWouW89nZSacfQl8Vf9m2junIUX/ePFnzAMi4OJxSO69Tq/UIjOL/YbWFknohwo4/rx9XG13am+2qNdW+VLIbvBFwiDRLKzUMhlHCeYZ1QhGp/B77jpzrPrRNg0BFmzygt3ETDeHGpyVtWFGUgJVVEitjtzcgUBGQ8ugTcKDpfnIhYjueHcBUlSvS8wsLahJ/GHOCt3zT8pH7WjUtNzAL3cWSmMSvMtWQhemxvnt00vOxaRvqZxggXXasdRDG2EcfibE0b7SpjbaFUnSHCl+XHLUnn5bOU2BitH2XdHGGela1fxsZDjFD2kmXWJVl7ExpV40K6Ltc82mM5k/8GtYNSwaOkM8SdT4KnOiiQwnK1/Nw7+xHDKwlX901K6T/Nwvztx4vrYL8qoPAXcd4
  template:
    metadata:
      name: volsync-restic-secret
      namespace: ntfy
