---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kecsi-san/ansible-env-setup.git
    targetRevision: HEAD
    path: kube-gitops/k8s/external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
