---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: "0.42.0"
      helm:
        valueFiles:
          - $values/kube-gitops/k8s/values/headlamp.yaml
    - repoURL: https://github.com/kecsi-san/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/kecsi-san/homelab.git
      targetRevision: HEAD
      path: kube-gitops/k8s/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
