---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "86.1.0"
      helm:
        valueFiles:
          - $values/kube-gitops/k8s/values/kube-prometheus-stack.yaml
    - repoURL: https://github.com/kecsi-san/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /status/terminatingReplicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status/terminatingReplicas
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
