---
- name: Tap HashiCorp Homebrew repository
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present
  become: false

- name: Install IaC tools via Homebrew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ iac_brew_packages }}"
  become: false

- name: Add VAULT_ADDR to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK — vault addr"
    block: |
      export VAULT_ADDR="{{ iac_vault_addr }}"
    create: false
  become: false
  when: iac_vault_addr | length > 0

- name: Add vault-login alias to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK — vault login alias"
    block: |
      alias vault-login='vault login -method=userpass username={{ admin_user }}'
    create: false
  become: false
  when: iac_vault_addr | length > 0
