---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: headlamp-oidc
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: k8s/headlamp/oidc
        property: client-id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: k8s/oauth2/headlamp
        property: client-secret
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: k8s/headlamp/oidc
        property: issuer-url
    - secretKey: OIDC_SCOPES
      remoteRef:
        key: k8s/headlamp/oidc
        property: scopes
