---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    server:
      port: 8080

    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: weather
                location: Budapest, Hungary
                units: metric
                hour-format: 24h
              - type: markets
                markets:
                  - symbol: EPAM
                    name: EPAM Systems
                  - symbol: AAPL
                    name: Apple
                  - symbol: MSFT
                    name: Microsoft
                  - symbol: NVDA
                    name: NVIDIA
                  - symbol: GOOGL
                    name: Google
                  - symbol: BTC-USD
                    name: Bitcoin
                  - symbol: ETH-USD
                    name: Ethereum
          - size: full
            widgets:
              - type: hacker-news
                limit: 20
                collapse-after: 5
              - type: custom-api
                title: GitHub Trending
                cache: 24h
                url: "https://api.ossinsight.io/v1/trends/repos/?period=past_week&language=All"
                template: |
                  <ul class="list list-gap-10 collapsible-container" data-collapse-after="5">
                    {{ range .JSON.Array "data.rows" }}
                      <li>
                        <a class="color-primary-if-not-visited" href="https://github.com/{{ .String "repo_name" }}">{{ .String "repo_name" }}</a>
                        <ul class="list-horizontal-text">
                          <li class="color-highlight">{{ .String "primary_language" }}</li>
                          <li>★ {{ .Int "stars" }}</li>
                          <li>⑂ {{ .Int "forks" }}</li>
                          <li>↩ {{ .Int "pull_requests" }}</li>
                        </ul>
                        <p class="color-subdue" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{ .String "description" }}</p>
                      </li>
                    {{ end }}
                  </ul>
          - size: small
            widgets:
              - type: reddit
                subreddit: homelab
                limit: 10
                collapse-after: 5
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                limit: 8
                collapse-after: 5
                show-thumbnails: true
              - type: reddit
                subreddit: kubernetes
                limit: 6
                collapse-after: 3
                show-thumbnails: false
