---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: forgejo-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: k3s/db/forgejo
        property: username
    - secretKey: password
      remoteRef:
        key: k3s/db/forgejo
        property: password
