---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgALkvVcZtEeEzxXrxn51uRj4OZxbpBfIWA7VPfW1HDhv6C3cEIptydK2aMyqKExsdH+LXTeEFONEOl8EZqTEUnjOh7NQosUQxb7iI0J/CiYmIAchlxaJJ0ZoVr9W8LE5Ijbmk4FRAwg7+2uPyI5FjeNhCZbecfgl4H18dHiIPBVi0qW5UVc6os0CHqz62kr+3IPIBn+WLoxO4+iLWKe2LNBn6QUI9p8f2MrS+N8vMExxnscq/7QdErKvEmWbrckLe7nxdGZkoLJo4E6LM0DfYoNc3YW8xZGlpiHoXcl5nn539ulenKer2v3+p+aQT4PCPClupbRWFxNyXDPlEVTJqqWs8dLEXITWYOpZ4mgQprD2esIjaYrzwtLNJV5gY2w03sqQZR2s2SPp3vkrSDuzzKlsaQuxQkVpNNKXbfWkULdQU/UUKAhquYvruP38JN3dzlX5H8zC+tuozoBLkn7FAYF7DHSRG6XjNajHmWxItGDLMvgBA6IkuUlH7Ivj4/AZLdxixClM4ri6rY/czY4wzQowFQntNVcqXcRLoFsHQd1SccRUUsu1EXvNsZDlG4C5dml5sxv3EMt0fnjOhWaHV09mxyO2kd8dbT1DB2Q5Qu3i3LOjwi9g0VPadMaJHduTgbtuRjg+qbRkdJ8NFAuVi0nEFDHC7ga3sk2gcUp7PVO/lQVwIEweGMnKUFQRuxMLZySfWcLtYu+eKUViMPem3haiICzAfE4Z6tPKdU4vRSRUkHCt6uMqDZWYNkd0AyH9PhFKujuHGFh5Gk94ARCzn8R
    # yamllint disable-line rule:line-length
    username: AgDSJ+2EtRHStsoo48yl82F5BV2eK/EzKFhM6QhjO/iMcGLI+UebxIYJH4x6omneYu75rroDgzbG0bHt03S5HhSJ6XT0wCLZZX2ehyW+EA1P/s8/OshvZJBjERvSd20+1qujVOKpTKtYWCZekG0mU4FoOWUhBrMn4h9P4NiSWEwgKj5dsHAhQKnlnezGUtehxrqYt3sOK/it728pNkZpQJklCbPUpYBfteWLC1R7nJKUTM4mz0+0KDQVxNhVbHowRKGaODwRrdbFpR7HFeZKIpjptNEayvczNGOQhkG3jJIEKfTQmJ7LSwtU13+dNM3aK55bvN0E9JfxhAZqEqMlXiZI86rDFk5YSoA+U1ycWooLi7CQBLc6dmVr+iID1+UyOZubf3SwCIpz+5CXhKETgaF20QOMZpucfq5CzBghp7xB1qc/69uTc8OiWyUwdmSNiQc0uh7HQuRDsQrn4YwqTevvvuZg8ekgMM+qC9VZpczbYCNtJzVTnQu8ySDPShlaXjC+HGde4/+AemxUFwz94UCu9kPXS61xhYlF/BT2jvSjTrWNEb4bJOhlz3vhayfu7Nt5DrEZpAYxMJpA12yLYnNIL2cjvp05dEUBkfDajdW6iHwu9DtpqSJm9zfaO2WTBHrMRrKgK64B7seN4xT6m8GSgoaw3n/P1WI52ugioujZ2coMazVFLoMjKBhvEZ0ZU/Cuz5tnmnI=
  template:
    metadata:
      name: wikijs-db-credentials
      namespace: postgres
