---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgAtMj613ZZ9L6fPWmEZ6eagVgTSr/CN4yPMsIZ+ZmbGsBW+q7DhY5x5D5F5k59gv77iphWApziqkDzOLvKBv5DZ5EJeeRu22+J7crwX/3c++XSR4e0yzpU1fKVISoMm4ToYZCCbZN7DL3LFzQ1x4hSi0/LDOZ61obvN1ZAm+Isr6g1niAkdgyz2m2/vRXzS3oM3MUpMG7D8SqCN1bqqOR8cvEW6ziLK/2CfRL9eR1yXJ8GL6LSflCycHAMFUMIq1nxIAn4yOU6tukL4r0vDyGfmPyGpnzpNi3kURiP0sMo1DYGRWUNvzQcsuUU+58nWZhSzgRbWuKECK1N9W6l+7QhoEcaobA18kmmlKLU8AGU2eI5EfnsxdksQGD9It1K+nrdRz26B2e/ZWyk8k9i4SJWBCIvmFN8WaWfTIvEVtuSE2MXF0+4TcnPSGyeJuJNVotMZcYGnq1s7AyNcEjid73bDWH+FB/+mVI7k67YZu8zzuuI+naNCfXCIDSXX+VbWepUmlL4cy+8Rsayxp6/n10eKLDlhLXrF13m63nMw1rGkCJRJ65ioTwNZB3CZpv/anS8F1H6AC4D4vwPSCL2z6gzt5DNoLaDfvTbYgTxeRytE23e6ohoYqovLto+5203xL7aIfHr9BsGTv10UpRmARcKMrKo7PllOHOwRm4oaC9MCsSAHG07kU/w/1bQ7zM/EWCnUa8EUS1B1827D4uTaSC++sYfj3xdaQLp5O/FbQmqi
  template:
    metadata:
      name: authentik-db-credentials
      namespace: postgres
