---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgDNbH5Cml4hGLqJ7uyofT7z0VD4Rt2W7MAK0NDaQLeyMWY8ZT7IUaJRXmh0mj77aGkIeuK7ubARKxWEYbiZWFNlW6ZafrlXd+H1uVSER2WLjhwUlLMJvhlRMa4zeSqdMLxorKEOUbWxNn+55qwWwhF3UbIE3jblVjddFz1LpB+JD34vF0n25ccuhiCnBrTqIR8Kcpd4mvKyELTknIiY3U90qkbkFINU+VuBs+08w8s6QzpbKs9MY3U6bXZfptB5kQjTDrLvocbNo9LueZGTe0eMJ9eol61gUTma3Im4g0lrYJkbmVqaoS4m7UceMELxyUDzor2yRxUGsPebIoGMI1YFkKgIio/h37jMkQ3/X5cdotmScix+2XTKAesPyalgn1MOxgrnlhyaAIALDinrRXgZjbh0T4yjqDgYwupjXSIGXaqOHgfSPe8gXAGaTBo77osHJkTYeUlxHuXCzQgDsfkJlYRYTAiudG0hZEuIrGn47kd6ozL7Q2IMVZES9UO65+poBBlL5BRjDHIR/91bN0tnS35c75STxAgNWH/Nu5qbOo3FJQIM4Wc19d5sr3OEzDR1JKGUljEKLKZOdD/seBflqy1khmMqvuUkV6DjukwVO4ITPwyTcu6CmlIKwArK56vPjuG19HXsxgJDpDElA7uLYNnpkSRrGcFEOgK+2S6I73lopFIEM+68qJ4PVDnYP1KOFFwiMWSzSsepTsvQz9ZmsCasTNzvYfiCKjS+BmVSPvaM6cieq9thKX/iyqNomT6exZ73Lc7CqqEjefv/DQ5I
  template:
    metadata:
      name: wikijs-db-credentials
      namespace: postgres
