---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgAZpulQIwqiH926YwZYVavv7iYJ9ryMht8s6jtuFRbvlkZ21q/xeGbG1XPA9S7hX0Kpx4e6f7r4Rbo+rbjdClkzjJa8t331yQTosbU/88TqMKTXuzF0wnazX8u5SIZ5jfcLNHt8zx9V3H4VOSRD36wky7ZqHWGIrxftwFB7b+hfzMoTesObcyJqdhXj0wX2j0+s6sZcEjc3ao5671LVhBB2AAz+1cMofoOSvJ4IKXQP9+P+KakOONL9crrx4ec1XAentlRymkZRv7PRPubaepitPMliWeH5PiEVrjWUDF4S8tO4IKvKxPseGgbVZacM42bbtuJ1bkyMgSJBtophewLOI7nS2SJP1E3R38oSSomk/1TFOZz6yD+zSxQrxPcWX+DHGSAtFmoYyEQXB4uHsD16XqWL1J4AkWyU75DYbQ1JNRFqJMPUmnOEoeGyEIk7LdbynkJuK6XqeRpdgSkZVbNsn8TlM1wrHbQR9eelCQWVJysL9drBe0N1rrPySbhk9TxSIul/EUXmxwGmgzUczjcymL9hi6lnRXyKowlLUdRV8gEipj+KhRA4+cpYeaz5/ZZumqyVNSbI7pTzBbxD9V0Zy7kQmEW5MVjzXPsSoEJUmueQ0k4LsfyUohQ5zkQCRozu6knUvUoPmgu4RtViPjCGn3TBMq7IBnSNvXGo55I7mKb7xV+dteo870jESMIYq3sKCbr7/DDQmEHhWAdwH6lxH4wVZiZy5qHyfOYoRWZVEg==
    # yamllint disable-line rule:line-length
    username: AgAWsZp2dTW7Rk2OQ2fxZ9NLzwgP+kPRFN72yQlBose8+yAqCx3s2pWPhJ/b2CDpzBEEZQ0aC/Qy2G9zHRKlNpTINv8heZVUM4YcbhNP4LRQjS7KhYusi2Vvs35TquIWFas86P7ggPGzB1ike38AUD49mfRDvr7eqXWNNwBwq4rNtrJwEPotLQ7EmJTfkybw1B8LODjN7JONSkVkx5FDzvR64l6gITwwLCR0wSe/It3w1gjzmStFpgJOwsPf8iH6WYAVYP0mUHIC0udjex3dAY30qh4BQar/2cbgPPSIP6rO6Nr5YFJ+yBho53SkIMDwnrmws/qSgnhn1VRZkRKz/Rjq1tSGS9+6UHlmzBFek99FXjRKCZ9eJWEHMEHHcvuGAY+X2W9q4WPJRFvFtQZa6X0iYcKiYckkxC8e/gzl1cORQAIqVmMzuxbsr8/BhrShWrB9UsBuYivku/W88BuWiagzpanC0J5pWf1THJMDKLe0ajXzzrLGPQrVGCqJTwWae3fH0EW1tWN54fn5EfbLPsWz9E1/UYDQNa9wS+Lx8EzpdtGtTsOCWmU+sUxmAir1AGTIXgPot0TfUMvk2RhCfnQrlssk7v6gzlS+FVuiqGL0qEeiH3+vmwqfGtl+CAPKb4ReeWkVVRTRd2mnQe6IvlQ6TfJYYdfkRYZEOk2XyK9s8QJZeRR3YkKYFmYBkpjBRXF14NGYJrEO
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: postgres
