---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secret-key
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: forgejo-secret-key
  data:
    - secretKey: internal-token
      remoteRef:
        key: k3s/forgejo/secret-key
        property: internal-token
    - secretKey: secret-key
      remoteRef:
        key: k3s/forgejo/secret-key
        property: secret-key
