---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-secret-key
  namespace: forgejo
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    internal-token: AgAby8c12y1g8XJMdehLDkFZg9IuAbAwjNkj1BBOXU5aQmsetvC1HDmry+t8ZETn0SLFga9bmSDuEe6C/+qxKht2S5jRrpJQkhrZTzdY0M9NvRIuXid3e9WqnLtB1Jaw8AjXMFeCThGC8Fx78jBUCgeaeu01jKO8TfbhDyc5uy4rWNQEPFqA4FYag9msmaxp9FgdnpUPNmvixRZs0YmmCR1HCA3VxOrVud/jBJqW+HIuonyXwE/10/EsCRDr2Tc88re3pii8De6QGFHX1biZ+IO678m5OJvoaUJoykjOql/vsmRZCw5u7Qu5jJpmPrdT30tuCzX6E2kEiJu9AL/rPyptOxsg4xcv9IujKixTRZyac7aC6Q5asc3pL5csvT3jf+/dz76J94fseq6AL/PmIES4i1CQN25grGS3RtINxbDd3UMNM4pT89fSXhTQ/cGZ59ACR59p2ySxYLkKwG4DjOUYHq4BSLvnrUiyUBDV1++CVtOsBEcKfkheh/oqqUyO/8BCVfhxQwxUwHYY4NuyRuttgO/TP45DK86ups+s7GiSkwgaal9Vs74djoSd4VYqyL92KQnxx9PCwoy1ypIy1ay4JBTHJBncR+R9LXw1+2ZRc/n2l+WR7WZb3QfLQLZJuc6nDOaluzjzZXJ5G/1npW4rB6+gMejir+pQ10tYjfUQhCSD4+5WpxnhV3ZuMBDlCFytj33rAipITHDHmj/v6nqDJvmK1XyWcka0beQ+9JRzfvSSHEv1pBoaL7gGZD5ZjsF3N4Og7ZWRHVB7L+31U+zP
    # yamllint disable-line rule:line-length
    secret-key: AgDBr4N/z8l1mgG0r6WVXxLYndN5UAK6n4NOSEKBDh/ZpCmxQ+ASTOIZnEOBZ/41vS8q8VtV23k5wsqCIkJzW1MIUVVKvNSXYj1bkLc3UBo3E8kIR/S3Gwvz9IoIL1IWUrbV7ImK21YptRH84Ll4k688GW2rXvsuZ1Hv8dJf/6YGrfzFnXaacIBiwYTTiLAVa9lKeduaj0dzZQD+lDSSw+jEhuqIJg43CX11NxZRJ8JgGwvIQRPKCQ5vCN2DVAtTk6lnNSuI5IU4eZhVEMugVACbXSSFCeyPussnrmiwgZSwS/245sIsf/Vt/L6hwL5hzlj3DoIxSh080Agc8HcT/Vu6CUAv68myYOl33+MhMTtUKfxyBoYm90txLvjww22aZkrRPxUKfrmOGxogDEjORNN4yphHIUXsj+UwM8Bq9J5bGTVamAASyPkSpsT3WGvBXgM7rQkn45CYKPy2TcNOWryH9vrBJ9kWzckbIr3qatM24GtwV3Z9PRoY+9naHDAeWWX0/XUdYnzm/U3+fvD40bp1TanGs/CImdbCEHzhMEc+TeCXmsjaYI80oOTiD2fnoFxm8gTwR4SXe3r14OEqQlrnQBSQLFul2F0y7oBh1INQ2OVUQyb96atD3xWxRmcZdXo7b83h/v3nzMBipg6uAotXtX3I9EKVoSZ8DANL0f3PkI9cbZGq62AuhpjYMNSxhLlKByX0SmZHfD2NM0mcyonYcFVEDDaNRzecPsMBV0tkAxZ3NkKa3cLmPxL7OKy76zdB5PZAe6kkjIn93ntPF2zL
  template:
    metadata:
      name: forgejo-secret-key
      namespace: forgejo
