---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgAas+lIAaNf2kqVga9n3+7rmRQrrSgPRXkJc3QnzhReGBo+x/ZY28cDGGbiziIbANE1qX7cpvjgS6Q78fJGG7KKwpGcpbJr+XFH89Gzl+j5sBNyAVM7Y8RQb3yfFv36okqx3xsDe0R5ep/uIf9Y+xYXBjIgVNfrZ1Jpi+bw6jF8/Qomlcy9hARAqObmNhokfsBi+sNQTdWteqGRdH6Dv/eShHcu94tZqtEiFertbRjvjc1uDuz9Jzm2/pN7riNPp+ZU+3Y4wI5stRG1KMeFUIi7Bc6TE6aUoOMJBM/Bjmz7qxlojMM93YUiw51njKXi+Lucd59gzfKXKaaKTK6KZp8LedeArSxjcA9zWahWqI0T5QvWp308tZefhhYi965SJSwrIhvrClEj25bToPRBq5FO3NlAGlbpOQmFiVGyinU40FvoBd58AO06TAu/Yun4RZjZqwngOlEJAn1xd/eD1eqOdZV5uFd0/jvQ4Oa9x38Wfv8bhJj4jmCKnBh/2amFBbNvkIpQDY9UtHjlWM9DSvuBsUbXxso0y4oHYzIBc+FEV1AzSFADVCBqtumlArZ26T58OWvQdf2Rpw/E0jv92RQm3c4R+IDPR8IQQkw7TuqdAR3LHj7uGLvVV494ZvOyzb54ulC9qyfpzHLq5pBUiTO6dCnwZA1OXDES3zAEEVFKR2VM2k7UFmc9Eo4o+ItftRYUoDSeZdnoqt6juHjDt+TI+K7fqiRRvPvkhRBZUX1KxQ==
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: forgejo
