---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud-admin
  namespace: opencloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: opencloud-admin
  data:
    - secretKey: admin-password
      remoteRef:
        key: k8s/opencloud
        property: admin-password
