---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opencloud-admin
  namespace: opencloud
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    admin-password: AgCn8apvzudS5kGdTTQFq1vtXBsdP9bwJMpeI3UPL8YVCP8C6XBIGEhO3bMaOtEJ96HrgOMJtvor3pyoQg1qJNzAJ3pl6CvM1FYSpJ0e7J8tu/gKyhZJA8V29PFM8EgdwThzB9Vy6GFBGwBqDERt1DTMPVdHFnXBWsFccZyTWQaQEG+BgyQ8UXvkYv+BxFm7FYQrw/Etnf5l1CXLtMx+iUaj0d1yfKe0DGUnOb7IWp7ZdfXn3AKe3kxD+TANXwSqcJ1XYfusW6tZPTd6p6oSPZqShFI1N0ddV1QW0tuZcVQUgRcDA3QtAiHfAjAuAdWRCyuSnGa6G2BNInSdkogpO1qPAT2F4V35CT5Fg8WpGli3YU1iR5zMBrAVTcGvsMhEaKkkeDFjzMICXMglKYx2gmSzrHhDIxx3QP4dO9renUL5iNspzZ5FYl5elNDohM9gAZ/X0u44Yealvh75ZqyVEp1W9WTIAySAc9rbPVrxDcQJhHubEanTW2mE9VSRvfB9QdaPC6DEUKHo0A43kGWowX7uKCqgqrSgSk364XWZWHxJ1iFtZn/7vy4KRdpvTRYpY7zc/y3V4Dd8SVHdqKPK/IF1OPXIL3sogFz14HSxBwUqqpMa2Jt5Avov2agCkorjyYVZtjzhCBWJ1TeltAaulivDt1+mgL1dod83agfESjYmtsk/bu53kIY4Mk/YatvSTwMeQ49Bw2oK4H0J7ywAYB/LqZNCmG6M45k=
  template:
    metadata:
      name: opencloud-admin
      namespace: opencloud
