---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-allowlist
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: minecraft-allowlist
  data:
    - secretKey: allowlist.json
      remoteRef:
        key: k8s/minecraft/allowlist
        property: allowlist.json
