---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-secret
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: volsync-restic-secret
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: k8s/minecraft/restic
        property: RESTIC_PASSWORD
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: k8s/minecraft/restic
        property: RESTIC_REPOSITORY
