---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-allowlist
  namespace: minecraft
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    allowlist.json: AgBHgKsbnHjc3vYA0OBHPK4q54eWPc1JSe8lAH2C89JmHfdkN9dCVaoRSuwUTU6vzLKtPX3wUH11W7+6Q6CUxphsZryQjabWGPYDK/rn9Ps1IGAMrNuXFx6Tz/Wa3fMQHUCsZg4hEBphLuJFWZybX78ASdb7mg8DUL1DDggwmnHd1DVToLCxHhkqvtvzfrAFPLNoUNW6ZV39zU4fHgY7ZQWwDpsVudUxDeyvRzHysBGCmWeWLR7gveOq+wUeBkMuNkExAEDUDyeNorgw5qypzPpsqMKZdkkh/kvSLX4euZMj7w/EabBgNN9qFbdr4AIJu/q2LDsL5aIViX3T4wuE2dGiuTNKPFb+vw498b5pVpXoBQigaOnIVxcKNlKmxYoW8WXNB+D42hdkAcGmwLwDk5aXG3NwtgBZhmI3X/cW7c9YP2sWMOZuQIMjdMD2W9VDscZynuhCb+2Lm9vsvQp9WyYJNCDNtVi/qFXRzyVTf9nGpoVaLWWsp4fBwOzASdMgkVLBURfIYjDATqtJfpqh7qzO82Z2SeoTtOH/zEYlZt37XkIWSKasGW7vshg3wJyhCUIF2TcG9RHp26TifX4xVHN0tAgocsAFmnr5R5knl7XZrXhW1Gs46tQQvgBghxL9qEbxh/7xiU7SFa2q1nyabvT6ZKldFCg5BemeXH9EAQZPjef31CSPHIZY+Uozk3wgQNe/XVeC1xRa2menWPi4T9ZHhcG86Xg+5OBiXL8tJ5drMkfv0Umivq/Hpo9Y1bw+qB9D6b1/M9/tBQBsLDAwDQPzj90PPSu0Vk/a+MUynfbRZt5R3gE=
  template:
    metadata:
      name: minecraft-allowlist
      namespace: minecraft
