---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-restic-secret
  namespace: minecraft
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    RESTIC_PASSWORD: AgCLKdL2+HOAjcxq3T+dJgYM/oGUyOrkuRDg6xY2tEDsDN01HV3OQnSgofbnVVjk28IPPG/Jdp2Tbynn93IFfJc3viYiRmaBrLLkml7h71DCdm9EEQ3zrUeRHaO2Eu9yum0KqCTTQd81/HniBC1nATsAcTd6CxxWAs9HqqGA3EAT3o12wORI1/68dcEGxG9UvVUza0jQ/zkNYHC2EtTMI0w2DgvsegYSTKC1jyER9MKmDb+Ur3KWp8S9lKO8x0ZI91VkeWcVW1dvC0fyecZX3A4a0n4D4nFGzKcK3FRTdAB8i4Ctd9syp3usb2GTy+ntiCvj+RWk4m7E3nVslQw0OoyOBidxAT7olMw5wt3bGnw333+p0PEXuVflUuZrmcocnlYeP2pRZf8ttEhz6oKRu8C5b6p/zZudm2qj3KvM5qAVEWMVIcUHlWsR7s6g+tnnDAdEzinuhBR7S0NiAgGO4itwT4M8+oBh5v6t5lEcokBfpazY2197sqCfP0OBq3h6sWbKzsZIRmE2TKQVwi2KNnpZQ6TywYwnezAoEWaRv2NjC74MQl46sgCCn9gCnAcb/WykSWxY2SyDbT5ynXKDSzPwloGYJCSBiK1vVjCKz21ShozgHC6gsnkkNh2iqaeXIDslNDoX+85N211UP8B3vp9KlaJACJOzyyQUoyxyFNZxZs4SBblBeAsotxNfu3jjOUkJBZkpy/3insfVGXGJyo0fSiedv/z1U2+B1Stq+6g=
    # yamllint disable-line rule:line-length
    RESTIC_REPOSITORY: AgBKH9i3xlTPcwm6Ls8bI2xC9TQRR09YaYJaihzhhnTI9IA/Kjya4Ud7ytuzjM0OXixGd0GD4GAq7ILDn5u2+5O98bNMgQI2kRjXz+PmmwG7AblHi1ivOg2uoFAUrOYZoG8e+lZggdoyiuNioTlW85HsZ9gRXKVqN/TferAaDz0locUaXNL5ND5X98s6Y7nQ10vkSuq8dbx14eajL7W/alxybwloAVwLXplR+NLZfLFNu039l3oVl7gMrqnAu6hbiL1MhqIoE++Pal5nM57c2eU6BfPdKDneVTLs7XOmFeIxmCMOhKvsWCV1GK7D3MMApDu87rUYwdikQdrtx63RlCteE/HZIGaN7pXD/1JUlPJ4bZiFR7kMnFwRpmwnTiQxhVQBgaNlmnTBVBJge8A5XdB4WwqQ4mLhEHcVL9mQNH6UFsYg1azLj4JaoaTxenPIqs9gW0G0PazWcsIIbw4WOxZantOoaCJmsU5PHUuCm6AnfZCbh1kSQD6H1Ga3Pr/EOYYLb5b1sLLkf0A8M91rm3+V8Y5VetzcsR+D/q1NC4Ead957LW8JnkPJeZnK20UPZUllQy67SCOYXkWAPy+MGLQJFBMCwv1FNuN3emvtt0XWU6Ko1SXOQgEfx2OORg01Q7Ud/g6kFQeaONFgRqMibvWt7AGNKgM+odR7OBQ6L3AHrPAIz2U/Mh2866QneIYyK+DBUsI2y48ZOj2JQ2XFGyAK1DygN3SgF4w8AzVGLwfSedv6gGjH6JI=
  template:
    metadata:
      name: volsync-restic-secret
      namespace: minecraft
