---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.1.110"
spec:
  type: LoadBalancer
  selector:
    app: minecraft-bedrock
  ports:
    - name: bedrock-udp
      port: 19132
      targetPort: 19132
      protocol: UDP
