---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-credentials

  managed:
    roles:
      - name: authentik
        ensure: present
        login: true
        passwordSecret:
          name: authentik-db-credentials

  storage:
    storageClass: longhorn
    size: 2Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: "1"
