---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikijs-db-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: wikijs-db-credentials
  data:
    - secretKey: password
      remoteRef:
        key: k8s/db/wikijs
        property: password
