---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgBUrEzXvemlZIpfYhwkaieT4vLMG0YaosKNyJQpTWW4xh4VUeATzfFaU81yCXRALweWu/nJ43+FG4dsIg3bN8T/C2/na/RCDv3ZeHCXr0i3wZA13pt3jD5Jighdq03e5y/NLqP9ygGyFH3/kbj8f/xANFxEYUJ6d7xe9PDhZGunNaLEAa+3hJ6bWlM7bdyujqtb0oR/6N3mXiZuncvhO9gD2M8JrpdjzAHwobTkLoFF9M5IcuJXwM5cPmy+ve403epSbfsQHbtqq+gly1n+RUHEEhgfvrtwOe+hQFSekPx0TfIDr4NoQb3WUZRK6XlN5vRh/pDJcvKpawrFzMNweZXJpH4Ewji2rz9TRP86oQgpvb+xdoMdeVkXzImsT9fS1Z4nLsD3Y7bbgf0rttQmLEnqHCNO6Xjo73BT2dS9ROqkoXWl5I2XP5X/wa7eyaTIT96n44/RoJev7Hob2kKwVsS+BzUbSzuj1YHReXUOLqvw3TKOw9II3WK9If6eG4fS3CLgU8L3JyRFW977+/E8iGaciyftM5w035718PwktN6ttIYgkbHYcYhqcDLaPuJ033YQDh6pyTsqEoYlLnP2VGmZH85G/gHkLSsIw/zutm33GGtzVAoFTpD7jRuKTbWcbukZ6Hz9pnIbeDn+2rRXvq5SnDIqg7Ito3++5ITBNcwUhx1GmUNqV9ZEBvtXdd84Hg11pxj3YslAGzxHyJrwC4QBskbEKckfvppCmLKECgSvxQ==
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: postgres
