---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docmost-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgA/FuTnn6goLlfF8StiKq2V7InStjSiRqzT/P1Hf+UYsduVkoPeawIiPJpRrJJ3tWdD3qVYp9laUqf6ChKm55L+NKdW9mlWxEbK14QtzFt1zzkRp88XlF506CqHnVIDy1azyLULq/TSwD9reSTz04dckbWW14H/6sh6W1H3TCMniXNTYkyoOyOGMVqKaBrEIZY3XegbWbla5bsKjXfAxz/o//Or582/sQPXeAQuho2+Z6XeoDzpYiBS4hbSqfTTogs9Pzq9Y3k4eB59K2Xfn7fERBiOp5Y82qtv++5JJwaeh64IlY5V1U0mo+tNaclKT99HcIaTYMWhzZoDWAaM+GCTYVzLHHcWEZAnWiF2FmybiiJvTaF91EfJb5Ggz9dc9PgUkAcoHvOIDCvrbBxjNpPQc47FtNKKKOY+zlSKp5WslYVeJyo9/XVhPQclj3OW2+dacXChfzuvrH0cRmS6U4tspEuXBYt3dX1HJsXRFJEHTwTG7lizipr4cFh3ACNCnOOwe6FOwM+PFDAdjy4LZ4AI5MFWaKiWqMOTAyKAu5zEwB6TC6T8D3yT9tPw6ibX3h23pMYEaFNIvFWPErcqMJOmKj55/bO5w5PvEbqAeZnYkrHUNrjV4QfJ3nrXJrqHsjEwH9bprhwvPJNBAZsCQMzWFG1tbiyOvNO5IZm6YdxzfamFBu9zGJWGmmAU23F2DDk6VWNtNmAvd5Ct5gXGuKAcd3rh2hgaa0ePvt1FCLKM
    # yamllint disable-line rule:line-length
    username: AgACtTWGYw/TVRNSk7lX0g+PjUWfP7Y1ckT33rXvPx25R0MXgVv1f97UOX1qwj329FAA3bhYIi/Q39ZaqUYC6MvrViJYoPBQ9nXHAZsIOV5aWtgfjGXnwLexYdril1hlgRbuNFdLmINgPOINbKCNxX0i9w74pDqbwlNXEfPWcpObQbmFq81U3Elsq1fK3Vt14L7NjEFFTeXym8z+ZxIzOROJuWGHlbiv8WEiF6FtGtgPXgGvCxQSg2y5qvdXyv8sdvp3O57Uqfk1YgSOiTYyljXcgNu8tKgJQGTYL5nIu4GCkx8tjsVE9OPBhVu3Dh/FuNZvFEqqdm/fhxZVjb1jYoZoG1SjF6fei15kXDq2EIkpEw/11sGFPXkTnYDPgBHYTkq+MKmRCeZtWdwIq7/v1oCpyNgdrTsPGtpfRTUb8vs03OkzoPivIqcwuuMsmjkctGIYbnmHzg2upXnQ416quGiYyYFMc4cq/wu6cIqZ0xYlIJeox5oWzNyYq8AYf3i7/QZRU2G+XbPWA4nvQz4Sm8s7YwKpVrdUCwBOsmOvbOqJWvf5n9NilrLwilN2bMdyfODT/tleCC3HaMTWA3qnjQ0whxZHroWnnO1nuAgNYnB/CuGnPXoPwBfynGG9L3pz+sh3rO7DPEDdUagdJ887nK83Sc6LxafE26Yf7e/mTqiuZX2dskrsQioqBH7seBG3cpkgCaPI5laP
  template:
    metadata:
      name: docmost-db-credentials
      namespace: postgres
