---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgCzFrhirkI6Iu1GbxptSTJQ4izTkyTJE0Q/aavbtl8h59VuwJwnwy+z75T/fedif9YBJFNzbL05GW+uPYppaKvjGe6+pHVox0Toes3CsEWFn9Be6OJUgzB2+o8AGWAOCi9VXw7I57nVu7LCZnPnPyM7TS8/MfBqrjwJIb7Ul3De4lX7gAgRUWrkmHj2bG849EHmxp86QV3y7vWUXCZ2gU61gX86PkXduryKFnqfUxVduzgZ6pHNfXc72kTaL/HO7Cju4SxupUhhNp/Fb+YhQl1pAhGQOq9+yCitCyK3GRqnDotFzQMRj5cK7+1LSwRsVOh+7mGVhjH1yOOi5ePp57sEPASMC2ku9QZoj290bmdfhvryV1ow2XVFCuqTz1roneCXIrKa3NiAyUKOjC6zAX+bEiH+0ZnHKRt+Q8SV1QCYYYk7X0yz1lxnk7TR1dcP3bhVh41HeoNg9oWFRDjvpPYXdOoKCMXh5kc+9D+Pd+MZBvfJmMHjGzfK1ViFaHGLD54NLY5CIsJLMFWHYCvFd9H8LWG2H0c89fjfKMJkECijSoHX3ciLlBf2M3/avTy7WwIESVYVBWp4SM/FJznWprFG4OH9BMZPWuJd0x0LlTs0vj81QBP2Z7+r19u6Y0tbAgM40n5fPXvzyoA+QYSTSGZ017GKcoWI6Sr99fd3W/nFlpOhFixDt2Db7ZjzqKM9zxifFrup9Bf4/TYRRBu8EQoWT7cXI8FNs44Fs4VnGRbC7w==
  template:
    metadata:
      name: wikijs-db-credentials
      namespace: postgres
