---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgABVazLbgyR8gYVCzfOp2V5AnjkNRrpFNR7+HvEhxyregBofPe6yWqlXXSOInQUIjAe3c4dwSZ5wr4orD5ZtzBxQunpq0ex7c+2cVWs54aRklB8riOTZ3bU+WGZu5G5NvTzPAtRJDJIcN4SzzwrpjlcZt+lDznLJJrWXKUrPpjBVWRg+kbz5c/CbtAmg5RgX2LlbPOXNBGZOuTpg6wgsx/PK/PmoKln8rdvz4NFpDgbP2IXTjAIAP32OHe9D6SPFgKlAX1XEvINjq4qpf3k0CdLW2HqXzTAz4GH4aPcNoskCzU8dgFon/1yB2rNgWonXDw24BaKXzlNtjY0r7eVghUj+gIyVMKR15J1hoa9F95/9gwqwTWWXW94rXtVAYEW9vfo068Yefg84NA9f/HEphaPTKKUxjcYyJUWMKl+YexlSBxrokrWO5U+wqXQBAY0626zHd8m4G2WNJa4sjNRMk4azwFZz/Mezoz8FNOVcMu1yBrOVrG9RVvKvyt/CDHjmfKgNhJMD+Dc4BlG5HAq4WRmDUxySh0fis5elJ7HOaSKlJqYihjhGx+4GN9bIJfcun3oXIOlKQfvLKxr26s4Q++VVFZSWJL5TXkKpLVYuXnHCa9z6aTg39zpbo97Hh+4oL+1Tj3Yj5DFqKInzwc48fRgQf3IRWb0bSLEX9hR8xKv3xhnPlylta0NC7RMbEo8uI8yrQrxyJ8wesfOihqyBZCgGht9ZuSFTk1HLwCAJeWhjQ==
    # yamllint disable-line rule:line-length
    username: AgBGKS8bJM57343gTqTN8oQhgCVxYzBdCvQ1YjAhaidNG4QwHifSiTGCguI67Q8krvMqT/o8lXvn889Y6wqWIqOh9DgGs5n8KlHo0CdbEsAJ2AEfX4F9ZSm8pVue319W1dH4MAeK6DUpn0a/Akg49MgCBkd4G4wtzh7fEQx+I4SBhmnOFaAKFausfu4WNng7ytyJ1QkqrQHi1IONIxlj2TfVEEGc07x3i9kidH0h4lH5wjlrh4h6qto8xtgGgltfNKes7o/rPaMq6OxcMQDaQaiLqDymSEzrGPSMATFqOlE1EXwkqEdM8MnSgSp4fn4G6fJriCmE+xG8UBBdZilpRUvVi1yHVD7UM6IMh8DJAYG7HkFBdb7XzLARR4fk74GcHiR21zKikvwvQSGnW44a4/nuy/xst5sYfhwT/GtGGINHIj0qmd0n8bsX5kYDJ5311U7K10MObCxRqaCamVsgZVcb/70zTEA2ImeK/V7TF+//785JqRmZITmFw2yOqy8+N16MEj/qjNP4sZnhn+I7oD/74J1lj6d3mT5H4yk3zc1cOkUXOtXmXjCJ85sLfd8UCQY3rYJN+Ti8D/PG3A3lv1e9AAOkqHI8NbwqSlkmBiwvpiOMffvUXBV2rpvQ+S4vdTqTu2W4gtaIqFro7GY5rP1Yb3OQcQUbp06BhY5opTWH3IFSXIZd/L/0vay0/8dRQJ+Iy65HS7lmO2U=
  template:
    metadata:
      name: authentik-db-credentials
      namespace: postgres
