---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgC5wDyC4A9Fzjnuxubrdzs73J8VS+NvE4ZOO0PrTuuPHoRemmPE/wt7TFcZu+ZO8vUpu8d4XtXz60mUR0ae7nHRIkz+i0o0xccssM1SolQnZgtvVibCNBAJo+VQVB3H4Mm3jLdsFUjjLRxlXsbCBUna1HHB/T0T4l39rFUKld87Cr2B8TXvHr3Xnt7MfhkuUZ7xBATXBuIdYoCermAHWQw2gMiTgUica4qCAGNOK3+0qMn9yTtxEIq4ndK1vfdtFwj6nHQqRY0+RE07EOClbhX74d56rdGVVBzeG8tnoTqzh93nslN0R48+yUJz672ypgrbNDUkAtVLN3DfbZgDBxHJxeSxeiLIHw5n2WGt1vVemBn+HPBQkVXz9hyMA35sw8foZFqzWw76bjLjewFpC/fDx+jCJzjiDbj2q60EctWlamixwEdxvrs2BK2OctV6C2PKOllNvPoq9RnYIdaAvykfndZZvOATO5PLBEad006DGAojocNIKHUStyWNI9x1Ru9VWoXfXj32jB8Spcwx/2X+TqOa8ukvXgQuBCjy7UVtdBVSUw45oEPR/Cep9lns9VPqcpNGZbSmxfudZ+QXGqDRv3El7cw0y+zXWS0jP4PNlu91LeKFXIWXN82MNn9OoNhxwfBuDwtF2SxJRht/lq2YDfWBtKmHBZoV8Zeezq9PHYVDr/6zyDN/tL42h/5FXMr3znR8ulpL5yc3lxSfRK5/CNfURv2fSpCfWzAraqendg==
    # yamllint disable-line rule:line-length
    username: AgCv+F/T4Fu3shhglJIuoMBUjqO9WaVRzajyJAKFEG0Wob5TvGtn3nBZQHXJg8syd9JVouyFwdnrudh8df/Xtpe+gh5I2TwXOsK3AwLwB9iiwvHgWvC/3C7u6xbuj+m0p9Y0D6jMkBmp+vlUxIZbF8Ll2Oz95zOX9MrSH1FKkQlfS3rYI05uo0doeAopWnsT1DCMbJ9s/tuvKQxDFa7GGcrL2Z2PVo1X6+juS/PmWO/5NtbZgHJicLigWwNzYbHOAQA1bskwynjU4LzDZyA3kIZUHWO7naqHEc0y9gDnfAtDdWDFAzSjJk3qgEmbL6A6qUUlzKUKzJjSIZOtYZAMAQ6b9vIEFgPXRoO1G2OsoJ/omAvA7zWawlIIxeLAhjSLCJ4FknrXBxLLJm9DWpNWk4m90IsZBnL5UataxoC/PaFQAmxT4dyBZDkmYxVFkk62LeXbOPkPKZV/Xy3gWPLimZtJsQLduLwVU33PLt0IPvjrSIYhZLKH7ph7gCAWm2o544gntoDK50SlvBfx9p/Lku1Py4CAOV8PptsTFP39S7EDKWUs5+LVCJ5c/jGWEhUEgyK5O9Xktpib0aU/hdpGN6kRqMpIMJ0UNnCEAi0t32ztnDTrK+EvFIFa4sX/vlIPh2w7iQ2T6dz9LQm2Ziyf/k4EplbJ35SIV7bwDnhthb4mDdu8j3Q/kwMtmyy8Xz6hFbYpHWYhEOPe
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: postgres
