---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgBbAn3MbXNHvgpBHg4vHE5FblJjo/z7xVNo6VmZ82eR0FH+NpiXFfB0N94BR09+Z/44xbC7tfKVxQx+3sRTIpQoFMF7EuvWUqJiE9JKUInW7cE3ocGaHMQubBBS+Mawv7EV1A27TttM1ZYCyZVIV0G5HWNwE8mrj/SOS85CVnmEygvfFw4QPgQ0urhM25P4knEzufVjtI2K5hm1XhCQJruIRsV/AyzJNl1uLIo3lThnaJdDenRV/IDUx+dWo9RA/xS6TRZb6Xw5IAIw6IuNxdV2yFXy3Iac4wdXMZ5OPpC80AHgjYfQMAifMPPlh8ak8xppX/priCJktfVbnuYooRY2q6Q5ehY1l0mXdpQab7gJuUnLmnueXA0/2XhgIjJeu68FWMzH1t7Wrvc3QZPlKgLqU26bzpaawHZVZOkBUv3RZaqTdy6sIWy9fUvYIrprQ8E6UGuLptyiSFYG7K1sVbB6deoRfYbSxYVwZP6WHYlv63sp3j3/yinQqMcHBvTRAcxpduasEHRXq5U1WvXAM81ZF7C6zx4viWWJliCpzONtcBR9lVvtaVr228dUoAqQRUcKueW2v+Z1593X6TaRnVcbFoSG7W3qCeh9KTjsRpiKToj+WIIN/al6hSNVrgS2qiXNN+77dewUnwnHUijWOqq+gC84YwU22owBinq/Ak9y69f8djuXgr6hcEuGpff0aoRRtHdKC8U1330kT8isk2dhg0hoiMUeZzydyNfDG38=
    # yamllint disable-line rule:line-length
    username: AgDTPFPe/ZbBnZM0Z1y5WbY/wUI4i8rzcarObCMeXtOAGwm+DD/1g+uQrEREkVXZYepQsPX8ye+M5KCqCTneEdli00y6GakyXkgHbCqoP1OlK4XH3pk5EO5sBvYt0AAqi1Hy2pgxn2xJKjWhKmJnhWVQa5+/y7vjxtiswLQWJ3RI+41kz8xBJNC2V9hWwI/nLoyVUvZHbXhUzr8Kmj1uZhYs1gvtV90sF0Ihvcx7pyzHam6CJsivtnr3Iwlg/YfWWjO/lE5htpcsdHOGumjTm9kMSRQEbGx7tncD3fWTnsRgSOWe5+2xAnTlSwkOnf3wE8yXYjtmbLqP6rNSsg47v26QxndjuIbl4wQecieeZ5Ho02pToBMdQ/cEucQetIlGdUv64Fe7TTJyGmMZO2BVZzLLuYrH6G+6hMU6Y2tYLXnRtCwzb6ieEj6gxBngIN3yT0yWD1bYliRA/tnTWAgtBRPW4OnkKM35IObFDIjI//b7bxeddG2VIZd7Z/boOQRVy/j/oyf1DJhDfZ7XuVhLkC5jBtjanB8+7r9N2oHxyp2Jm/uA36BetpaE8bTTc2qEx286YL4fII/LBaceScn/pg1fArWx7iuWHIoeaQIlXXCse5GIGrCmlkvtvTTopr+xa+/iR/fwlj1LzNR6+k4LIdi9+z1xX3wVuX0Lutb/OY9/ezKT/uOV61dHosoKUX1E8CmyyfN/2cEp
  template:
    metadata:
      name: outline-db-credentials
      namespace: postgres
