---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-db-credentials
  namespace: postgres
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    password: AgBHA9Ramdfcv0z4yJzLRnCFdNMqLNbhbON2bfsM4TTp0i/bWCEk0Zz3As4pUZ407qqjE5FBRSRPwlhUD1dOLKBedT1gVRrr8FqiZqs38eeBz2D0H9PHt6t36U5Mm1NEAVi5CuRG8VgjOiA7mgstnK6vZPxIcSO9QAEPOtGUgazGB4tfxzmkCYhC0bv3z2TnWaqkHCEpQCXCLzW9LvYByRzU18dXTyBOec06WVSC3DI9Rgf5wjUL2aozS4ZM8aTeeZZrGCrSiUqndgnH0cpngnikEX7NgQFntYtUX1PH021cvjHAfGsMs19TftHfwZMeOrDrBQoFWRE8HH2oPrlEBnnPzEr7bYvyS2kVh+nJbFt4cIcxy6pXeU2ETiJinNGMQyKleBM9nxGqdDO3EyqV7UbvHhPMjDpgDNlQ8L5r2B0NOerMCMeSXLKX0BySZyl9slX6jQ4Fb541Z0fOzv1MUgBGv8BlSz+YSj8n/YvRXkl5qg+qFQYo1XFQ2Nok2QG+bmMRRzLw7BvueSIzTY/r5NEwmGG4SP6BdmS5+UTmhei69LYTlmAu8Tgr5Zr82zhBq4cWZbFgDXzz2ARKH/Hc03Tvb7Ms0QYC663WvwCiCRqzJSBq35w+fq4RrqzjZbkOf8/YJSJxOhQbhK6Dap8sEH4bgsj/R2Fxhdlnv0Dbk1Sjv2I06mxBmtKBBjvxpnbHKRKPpsxhIRxb45T+lObo2rh1Hggiv8B8w+9vk/eHuPsmCw==
    # yamllint disable-line rule:line-length
    username: AgC+swPkZYfFlXS/DvAIRhZrlbCGAwyH0El/5WchOiXtuglI5r38Cj3c0HsicAHLYSrXb+VKCNhweUAejB+748JQHB4MAnBE+cYoRaKgWRXGZ6Eb1pOejtZg30hyQBVaDCoJ1uGMo7dFT/RZIzYhL2u/wd01muP3GR4CJ2lXK87NQ7Wgu+nNrPbCrHOjrePLe9/uqwt8bFqrCLhU9by6XiqMSC1QDXlhfn+md4ThiCiwkZgwrUmCV9eyhHbn0FOrdh3zKHPtsNP8jbHboE67hP8tQqRre30spstva22tseMjujHLs0TLBT9MrTxSG5nOE92yaPiHdWS/kxKpPw4I3wX7x7QsIYB/abc3jOyrJN6JR8mA+faEqf/o3yxXWN08DVJbhDrywH/b/84o6ZGGpQeLIDieVCjwleWLZAO0vCAmdYGA3KbZGVaMmqE1GBNadfX+zoQebPRDrxl1O9d28fWoTl71/ED0+whCehcw8Nio4Kz3HvFXcMMAvHj2NC4ErRzfH0ZDRVZNJhDyeiKoru110jLle0HRzTqTxm9XExr7IcDRxKraqy1Rjrx0SKymYSYEvy3MQ9D++CnCBdY1xSsyUli8N/XDAjEjGcFqpIP2RPwiFJioeXVH2rI24fcBGbl0YGqB9ILvJKv2PS8doVpgEcNuGdtEMd1wtSf7zIpUg/cr614cVJ6WDP99v+ozjY/JLxjkN0FgVro=
  template:
    metadata:
      name: backstage-db-credentials
      namespace: postgres
