---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
  namespace: monitoring
data:
  config.yaml: |
    gallery:
      enabled: true
    badges:
      - id: debian_version
        query: label_replace(node_os_info{id="debian"}, "version_id", "$1", "version_id", "v(.+)")
        value: labels["version_id"]
      - id: kubernetes_version
        query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
        value: labels["git_version"]
      - id: cluster_node_count
        query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
        color: '"green"'
        title: Nodes
      - id: cluster_pod_count
        query: sum(kube_pod_status_phase{phase="Running"})
        value: humanizeNumber(result)
        color: '"green"'
      - id: cluster_cpu_usage
        query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
        value: string(result) + "%"
        color: 'result <= 35 ? "green" : result <= 75 ? "orange" : "red"'
      - id: cluster_memory_usage
        query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
        value: string(result) + "%"
        color: 'result <= 35 ? "green" : result <= 75 ? "orange" : "red"'
      - id: cluster_birth_age
        query: round(time() - min(kube_node_created))
        value: humanizeDays(result)
        color: 'result <= 15552000 ? "green" : result <= 31104000 ? "orange" : "red"'
      - id: cluster_uptime_age
        query: round(avg(node_time_seconds - node_boot_time_seconds))
        value: humanizeDays(result)
        color: 'result <= 15552000 ? "green" : result <= 31104000 ? "orange" : "red"'
      - id: cluster_longhorn_storage
        query: round(sum(longhorn_node_storage_usage_bytes) / sum(longhorn_node_storage_capacity_bytes) * 100, 0.1)
        value: string(result) + "%"
        color: 'result <= 50 ? "green" : result <= 80 ? "orange" : "red"'
      - id: cluster_argocd_out_of_sync
        query: count(argocd_app_info{sync_status!="Synced"}) or vector(0)
        color: 'result < 1 ? "green" : "red"'
        title: Apps Unsynced
      - id: cluster_failed_pods
        query: sum(kube_pod_status_phase{phase=~"Failed|Unknown"}) or vector(0)
        color: 'result < 1 ? "green" : "red"'
        title: Failed Pods
      - id: cluster_alert_count
        query: clamp_min(alertmanager_alerts{state="active"} - 1, 0)
        color: 'result < 1 ? "green" : "red"'
        title: Alerts
