---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-homelab
spec:
  provider:
    vault:
      server: "https://vault.kecskemethy.hu"
      path: "homelab"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "a38d9c20-cf42-8e14-ac5e-c380d4c8d34a"
          secretRef:
            name: "homelab-eso-approle"
            key: "secretId"
            namespace: "external-secrets"
