---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-eso-approle
  namespace: external-secrets
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    secretId: AgARhWv6RcM9s+7izQE4d/Vg2RpLBgDK7sre+A6MHxDPdl8ArUSkYd/Gx2oVS716Y0KesnZnpbcDJTm20Pc6d3Eo3NFyGsHaHs2PSmgPqhx0CF+V93IoM6svMTOyFIxCAXRBYGSd0PPZkgAMgzUtbr/PaaRc3737scUJfoDUMnGpKoe9Q7OxD/xMH8MTObeSihS4zScSrukvw4HhOVu2J9DG0RYqMVa0FQSvg8CKCG6UqGMj6JhWlaGmOOHHgB7YXP+2PdZs2a+8ZE0xlMAVxTUgUHLSjPVg15HSfaXvCKin71NdAWt+vIhCyyQqWNdK137H34CfW6jNCFo+z3CtKtVvmYt/sG97UbVNEnqG/L+hASxKHyvSTuuTyXZQNPpsVOhF948eGZQkfWuaU+zeyU7/aJoHRwKy9x35mooeJ+rWloTzRODs+qVkwDzc0ADyhwx4kSjchw9sQm2hkG9N+7mQJWLkIHsIhnahJmw6bhlueI+cbPdgqy+iNFOeefnTQAWt/uezVKCFblaA9s4k+ky8t0bawAV0a+1zwFnM7W8Z/kdRN443SCc4kNLqHJAge3oPi7BOh/5IuvYXp8loVTh3EqGE+CfukzqrcM7HuCedOqpSN7InS2xcY+LDvWHxe7PURu/MUGaJSmmC9LB9Dvw4PypWzWqnIkoWiG7vBnm1evhSKFvQWRwwEqaRXR9vHIbxl0AIS/gXQ1yeS+Y6Pg/L78kGKLM7ZrsRTxHXaUL50IebUnc=
  template:
    metadata:
      name: homelab-eso-approle
      namespace: external-secrets
