---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    admin-token: AgAKDIx014a5tpad15m20ByRYWIt3qtg5SxVgW6mQaOjbcZeG0l+DtUmNYeX90DRLIjCmAtvF5t1dnKSLMFM6GwIts4yxocNVwoj2FO1hD9Fw+fw20BOmB1mNZCl5cQ/gJC49tN5WEJIYkQZkGSgux0ta4PjJZRiWXx+3FmpA6JZzSW7OG0vBXVi8s/PswH39rOYP+mkiO9fnhjN03hiET+HDXVW9YUdKykmotoMRFD0nK/J328bQ1MmEM10/X3pJBkE8oXkgr3VDqp99WUqwP0i/0Vlns9fT61kEliIjrj+WcbJNQ3R1CaiztNuqrucqJ3AoBqKflnfNlltnQqd0GoyGRfcnnl4CZHCbOO9XU7D+24CJ4H52Lk0+a3RnzW5TY41ECfthSWayv7r1yOIuRDu4xA1aEDNFesG8AMgckOzltbY031TovkLePl1FmDRp0X/iCmjZIeR0zBLFWsxjpjOlkVoueAdc6qQsfh43Q7fWO4ZCNLhqwVkHQHjkaLsmEgDpCvpeDwlXfISsNGLjrrefENwzeZwrm537Abhk1FnXMkKiQTe4Unpe5yLtOeR49Oml311sqAECmI24zUnSbfUlFfMXO+zEJROgrxSreUXimT3BVjv0wArIxUQtx+l0tu0utbZeXFrGqlNwSfPel5WW34aZvOv2DyFTmliMdP6Bhu397tRpWZbJ/2lxi11cbgJTpgs1qwaiZZ425gzRkvIdmM8LnqcZfmDVMcgSe/VT8B8MBAv/Gs5jRwYCQ==
    # yamllint disable-line rule:line-length
    rpc-secret: AgBUwvmkBuXcSRuNourUtrZAwo+Xx6ImWa+8p/sPYRCLSuZqbMJydS6HshiNVaF4KRKi7vrE6txpPHCpbUCNfnTGE2ha23ZWoXiIPBekExYhMHN3DZ1yeWh5wz7wi2OcpCOV7fz2Gq7DzwQf9UVbKRDda+OnUEe4OShaqkL7MifMo7DJZfVuS9V5f9INrAZtbF7WofswU5OxIt93tBXk1P79SMZizyLmW+/2G8kxskKfdUOQ0EZiA6XM2qLn55WOHZRIraLR3PW4MIAufG2jynou0pia7qnqHiXrebzHbU90XH7E00Gj5idlpSfepGMeXMkPdRB5AfV+jeQba6gJwvlPeZLyT7OPq0kM9wlcr5Lm7Fw7QCG4Zs8ZnCwasNBxiX6OZX3Sd7QvdzT5SlS/QM/J4l7BX8QEJ69eHyaAizVVvPaNy19zbm8/5az5yrZWlKB6F60q4NqwYUWW8HSQfkhlzFpgFQdbj4UYoC2AwckDa+geg/tLupyx4ZdVoJ3jAtZXO8I6xlnX38U3tCDCnLcZpsYXnKN8N5wn1NJz+e09JRxrMeEkF6bDWugN9f1GyThw9nqfq+GDrsRM/rjz1QLl3Oh9UvjNlK/vvfpF7FpEEq+HM9s29hEKKt9Z6InLN379WRbJ5yjK87lCUE0qeJpnNlE7MpP4/8U87LHW6DFvJg9/wZV867lgZMsvscrUU/wP1e3i1GMRc7W4murg3htmW9ITluSlkRp4EJNF3MEl4kpFMLquQROJ5IJUft8wdEHpADVjvyu5n+3Z4EhV9ChY
  template:
    metadata:
      name: garage-secrets
      namespace: garage
