---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.js.wiki
      chart: wiki
      targetRevision: "2.2.24"
      helm:
        valueFiles:
          - $values/kube-gitops/k3s/values/wikijs.yaml
    - repoURL: https://github.com/kecsi-san/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/kecsi-san/homelab.git
      targetRevision: HEAD
      path: kube-gitops/k3s/wikijs
  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
