---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-token
  namespace: forgejo-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-token
  data:
    - secretKey: token
      remoteRef:
        key: k3s/forgejo-runner/token
        property: token
