---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-token
  namespace: forgejo-runner
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    token: AgAiLXaR620oMBgQsBgz18oWD7k5WWRIOpaWqkb30tFWh8/exLBz9+sHKYIUygntjtgQnfjOdt6FfAbl6IJ2IkIv3shJCa97K1Mv/dkmZL4yNPH4ZWnxJFBJ3mj7Zf6NI1e4HhmGT4xG2lVOVn9oVIfsk3CoiTGoAqKM1UfJHOLwzQclEl2ska10AqMVUtqZBelZJKm9+CzM8YfFL/C5VdtRiuOAC3Sz1S8v5gIJi6KYHROUSZURfmCRtQkqVUHS0wW4Xe6vxFF45Be/4z7se3khiP/qICUDZ6QhFN1sp0xk2qGY/iVFTopOtagkcR14ztpXanhXuZfEXxXeTWR6IM6+8p3QD3fp1kLwT5y1xWNdbmtR8f754YyqhhTWBIA1ciKmkDdAi7u7eIxBALyVyXytwjxiXuHyc+lSF372GQ47kYl8dG2WAnyNfSgeioBgGrH7CflxUFppr56mhuIONIqBzi/dY4Q8sW03tVgn+GUlWYZTlDUsxGMKTbJ3UFaRsP1PZJ6X6LNIUdq5orZtNP/pdJ6x0GMVYXOGN6qvGuk9NV8MIFEPv94Aju/zZOygxlezndOc2aoAsQK5RF1FaGZInit8Ok8EYy2RbleWXA607S5AFKO+qeDSapJ7hO8i+zYUOijVZ+NrtoCNfCoRWqx+0WfNS7GW9h9lOmF0lWn1OEdM/24jme+LOpijXN88qWljsCY74BxhvfrSR7e3qIHL+j+2F0p4U8PxY+Fn4ovzrMDevCU1Winm
  template:
    metadata:
      name: forgejo-runner-token
      namespace: forgejo-runner
