---
- name: Configure Kubernetes nodes
  hosts: kube
  become: false
  remote_user: "{{ ansible_ssh_user }}"
  tasks:
    - name: Upgrade Debian packages
      ansible.builtin.import_role:
        name: debian_upgrade
      when: debian_upgrade_enabled
      become: true
      vars:
        debian_upgrade_enabled: true
      tags:
        - update
        - maintenance

    - name: Configure SSH
      ansible.builtin.import_role:
        name: configure_ssh
      become: true
      tags:
        - ssh
        - prerequisites
        - developer

    - name: Configure sudo
      ansible.builtin.import_role:
        name: configure_sudo
      become: true
      when: ansible_system == 'Linux'
      tags:
        - sudo
        - prerequisites
        - developer

    - name: Configure /etc/hosts
      ansible.builtin.import_role:
        name: configure_etc-hosts
      become: true
      tags:
        - hosts
        - prerequisites

    - name: Setup legal banner
      ansible.builtin.import_role:
        name: setup_legal_banner
      when: legal_banner_enabled
      become: true
      vars:
        legal_banner_enabled: true
      tags:
        - banner
        - security

    - name: Upload profile image
      ansible.builtin.import_role:
        name: upload_profile_image
      when: profile_image_enabled
      become: false
      vars:
        profile_image_enabled: true
        profile_image_file: ".face"
      tags:
        - face
        - desktop
        - personalise

    - name: Upload favourite background images
      ansible.builtin.import_role:
        name: upload_fav_bgimages
      when: bgimages_enabled
      become: true
      vars:
        bgimages_enabled: true
        fav_bgimages:
          - green-planet-fantasy.jpg
          - jupiter-auroras2-2560x1080.jpg
          - lorand_fenyes_hold_0023_sarlo.jpg
          - lorand_fenyes_lunar_pilot_apollo_15.jpg
          - moon-bw-2.jpg
          - moon-bw-3.jpg
          - moon-bw.jpg
          - moon-space-art.jpg
          - saturn-planet-dark.jpg
          - starry-sky-night-mountians-5k.jpg
          - the-moon-surface.jpg
      tags:
        - bgimages
        - desktop
        - personalise

    - name: Install nerd fonts
      ansible.builtin.import_role:
        name: install_nerd_fonts
      become: false
      vars:
        nerd_fonts:
          font-meslo-lg-nerd-font: true          # recommended for oh-my-posh
          font-fira-code-nerd-font: true         # ligatures
          font-3270-nerd-font: false
          font-agave-nerd-font: false
          font-anonymice-nerd-font: false
          font-arimo-nerd-font: false
          font-aurulent-sans-mono-nerd-font: false
          font-bigblue-terminal-nerd-font: false
          font-bitstream-vera-sans-mono-nerd-font: false
          font-blex-mono-nerd-font: false
          font-caskaydia-cove-nerd-font: false
          font-code-new-roman-nerd-font: false
          font-cousine-nerd-font: false
          font-daddy-time-mono-nerd-font: false
          font-dejavu-sans-mono-nerd-font: false
          font-droid-sans-mono-nerd-font: false
          font-fantasque-sans-mono-nerd-font: false
          font-fira-mono-nerd-font: false
          font-go-mono-nerd-font: false
          font-gohufont-nerd-font: false
          font-hack-nerd-font: false
          font-hasklug-nerd-font: false
          font-heavy-data-nerd-font: false
          font-hurmit-nerd-font: false
          font-im-writing-nerd-font: false
          font-inconsolata-go-nerd-font: false
          font-inconsolata-lgc-nerd-font: false
          font-inconsolata-nerd-font: false
          font-iosevka-nerd-font: false
          font-jetbrains-mono-nerd-font: false
          font-lekton-nerd-font: false
          font-liberation-nerd-font: false
          font-monofur-nerd-font: false
          font-monoid-nerd-font: false
          font-mononoki-nerd-font: false
          font-mplus-nerd-font: false
          font-noto-nerd-font: false
          font-open-dyslexic-nerd-font: false
          font-overpass-nerd-font: false
          font-profont-nerd-font: false
          font-proggy-clean-tt-nerd-font: false
          font-roboto-mono-nerd-font: false
          font-sauce-code-pro-nerd-font: false
          font-shure-tech-mono-nerd-font: false
          font-space-mono-nerd-font: false
          font-terminess-ttf-nerd-font: false
          font-tinos-nerd-font: false
          font-ubuntu-mono-nerd-font: false
          font-ubuntu-nerd-font: false
          font-victor-mono-nerd-font: false
      tags:
        - fonts
        - desktop
        - personalise

    - name: Configure oh-my-posh
      ansible.builtin.import_role:
        name: configure_oh-my-posh
      when: omp_enabled
      become: false
      vars:
        omp_enabled: true
        omp_themes_dir: "~/.poshthemes/"
        default_omp_theme: "debian.omp.yaml"
      tags:
        - omp
        - desktop
        - personalise

    - name: Configure fzf
      ansible.builtin.import_role:
        name: configure_fzf
      when: fzf_enabled
      become: false
      vars:
        fzf_enabled: true
      tags:
        - fzf
        - desktop
        - personalise

    - name: Configure git
      ansible.builtin.import_role:
        name: configure_git
      become: false
      tags:
        - gitconfig
        - git
        - developer

    - name: Disable hibernation
      ansible.builtin.import_role:
        name: disable_hibernation
      become: true
      tags:
        - hibernation
        - server

    - name: Configure NTP
      ansible.builtin.import_role:
        name: configure_ntp
      become: true
      tags:
        - ntp
        - server

    - name: Setup minimal packages
      ansible.builtin.import_role:
        name: setup_minimal
      become: true
      vars:
        install_base_packages: true
        install_brew_base_packages: true
        brew_base_packages:
          - fzf
          - gcc
          - git-delta
          - go-task
          - just
          - oh-my-posh
          - pre-commit
          - python@3.12
          - uv
          - yq
      tags:
        - minimal

    - name: Setup network tools
      ansible.builtin.import_role:
        name: setup_network-tools
      become: true
      when: ansible_system == 'Linux'
      tags:
        - network

    - name: Setup security tools
      ansible.builtin.import_role:
        name: setup_security-tools
      vars:
        security_apt_packages:
          - fail2ban
          - rkhunter
      tags:
        - security
