---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-homelab
spec:
  provider:
    vault:
      server: "https://vault.kecskemethy.hu"
      path: "homelab"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "46d39334-dbf6-0809-a5ea-87c0b92aeadc"
          secretRef:
            name: "homelab-eso-approle"
            key: "secretId"
            namespace: "external-secrets"
