---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-eso-approle
  namespace: external-secrets
spec:
  encryptedData:
    # yamllint disable-line rule:line-length
    secretId: AgCdCqyFtfe0jqpf/kZjzgCeeHkAl7gzayfO1eQSCav3YDs9YYDC8/cIyz0TtV4mQX4y7gGdNQTIGE4rc/LXN2Dp2g0/f8y7EGgP4qkjChv2ECOEIglHP2+XCf5yNxfxe1V7rRemTBnmFzQR4TxPsH+u3D4wCA/4u+5iyEC9EScSsTpm+bv6sQiRLl4u8AvT3iIjTCthcJJvnY7Eu+PUBd+uvgZW4Y1VhmN5WtGYl4gOJxbQN6LSSasF1ZCL5kMwMpoSY7ibxu2aZQ3bjnG2yePwE49IC4X3SpzZtJV2WmrWtJgbdSIfUYnACvVAAOXMftIjQFvL2zERVEX9/qYvaBKHnZ4yHfwx8Rnbu1fLqVMc9E+tnncQL5Z1K0jiKXLqT/x7TQJ/H0ifUSvCfpY/2xFZFEi24uf2KTAf2j8rnAVVb95Mf9Wbm6yxLK8i/jeUrY1MmV6pTycVrfQoxrAQUzhRAxVfZaNcgpu3ryBYVKQIpKewA7DWooFxi3B1NGem5EE51VXfLF4o2XDC2GMbdszToS/OwYUtgFX1nrnGC1QrqNT0IleGZ1scDzpMlmbrqBnbWWpfMXLQRTV4XdTpNYS+wip+lo2obpRO6xOw1RUpr0djiCQoO3eyNX/XhicgHM3F8/nCSl9OSxAMU6pVznPDk+v0eZUmLB1qD3Ft5q8fQFHeLmuOyoKlUycCX0m9h2BnbVZTi0JynGiX61tQzuWkpsKuqmWxkVvfnYN4aJlChdXNV8A=
  template:
    metadata:
      name: homelab-eso-approle
      namespace: external-secrets
